### ISSUE TITLE
Issue while authenticating in control-panel.bat when Replication is enabled on multiple baseDNs. 

### ISSUE THREAD

**Issue by himanshugawande** [OpenIdentityPlatform/OpenDJ#111]
**Describe the bug**

In my OpenDj I have configured more than one BaseDN and when I enable "Replication" for atleast one baseDN and then when I try to authenticate using admin login credentials in control-panel.bat it gets stuck on the same login screen for long time then gets disconnect due to connection timeout error. The issue is not seen when I have only one Base DN.

In addition to this it is found that in access logs of OpenDj the below provided search request takes a lot of time to bring response also,

SEARCH REQ conn=0 op=256 msgID=257 base="cn=monitor" scope=sub filter="(objectClass=*)" attrs="*"

**To Reproduce**

1. Add atleast two baseDn's in the DS.
2. Enable Replication for anyone of it.
3. Now run the control-panel.bat from [OpenDj_HOME]/bin/
4. Enter the proper login credentionals and press enter.

**Expected behavior**

It must successfully get login and the control-panel window must get open.

**Screenshots**

Screenshot 1:
![image](https://user-images.githubusercontent.com/60377982/78753336-3c79f380-7993-11ea-9991-a7f21c7468e5.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/60377982/78753400-587d9500-7993-11ea-8e91-5117ca853e2b.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/60377982/78753452-6d5a2880-7993-11ea-97dc-be9d1d363215.png)

**Desktop (please complete the following information):**

Server OS: Microsoft 2012R2 / 2016
Java: Same behaviour with jdk1.8.0.144 / jre1.8.0.144 / jdk11.0.1 / 13.0.2
OpenDJ version : Same behaviour with 4.4.1 & 4.4.5
Replication: Multimaster Synchronization

**Additional context**
Infra is on AWS.
Firewall is disabled.

**Comment by vharseko** [comment]
cannot reproduce problem with docker
