### ISSUE TITLE
Sometimes connection with OpenDj is disconnected by read-timout error. 

### ISSUE THREAD

**Issue by himanshugawande** [OpenIdentityPlatform/OpenDJ#112]
**Describe the bug**

In my OpenDj I have configured more than one BaseDN and when I enable "Replication" for atleast one baseDN. Sometimes the connection of OpenDj with My application gets disconnected due to read-timout error. I have deployed my Application on Amazon Cloud. This is very intermittent, happens once in a week and gets fixed either restarting the OpenDJ or my App.
When this issue occurs, there is no issue while doing telnet to Ldap port 389.
We are experiencing this on couple of environments.

Following are the logs:
Mar 24, 2020 15:17:34.182
ERROR:  className :: getLDAPConnection : Connect Error
LDAPException: Connection lost waiting for results from 10.20.3.10:389 (91) Connect Error
java.net.SocketTimeoutException: Read timed out
    at com.novell.ldap.Connection$ReaderThread.run(Unknown Source)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.base/java.net.SocketInputStream.socketRead0(Native Method)
    at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:200)
    at com.novell.ldap.asn1.ASN1Identifier.&lt;init&gt;(Unknown Source)
    ... 2 more

**To Reproduce**
It is not reproducible and happens very randomly once in a week time. Apparently, this has not been seen when replication has been turned for more than 3 weeks.

**Expected behavior**
It should work fine, all the time.

**Screenshots**

**Desktop (please complete the following information):**
Server OS: Microsoft 2012R2 / 2016
Java: jdk11.0.1
OpenDJ version : 4.4.1
Replication: Multimaster Synchronization

**Additional context**
We have been using the app for last 5 years on similar setup. We never had this issue, recently we have migrated form Forgerock OpenDJ to community edition 4.4.1. and have started facing this issue.

**Comment by vharseko** [comment]
try 4.4.3+ https://github.com/OpenIdentityPlatform/OpenDJ/commit/dcda9784b269635626bfc98d819d429c39a1f8b7

**Comment by himanshugawande** [comment]
The issue is reproducible and has been reported by our customer as well. So it is not one of a case or infraspecific. 
Here is a couple of more pointers that might help.

The issue is only seen when the 2 instances are in a different data center. For example (1 OpenDJ instance is in ap-south-1a and 2nd one is on ap-south-1b).

In my on-premise network within my LAN, I have one data center, I am unable to reproduce the issue in this case. But we are able to replicate on AWS.

The customer has 2 setups, dev, and production. The dev setup is within the datacenter and the issue is not seen. But for prod setup which are is different datacenter, the issue is observed.

Also, we are customizing the schema, not sure if that is related.

We are also enabling the replication using the below scripts.

"%OpenDJHome%\bat\dsreplication.bat" enable "--trustAll" "--noPropertiesFile" "--no-prompt" "--host1" "%LDAPServer-1%" "--port1" "%AdminPort-1%" "--bindDN1" "%AdminUser-1%" "--bindPassword1" "%AdminPwd-1%" "--replicationPort1" "%ReplPort-1%" "--host2" "%LDAPServer-2%" "--port2" "%AdminPort-2%" "--bindDN2" "%AdminUser-2%" "--bindPassword2" "%AdminPwd-2%" "--replicationPort2" "%ReplPort-2%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsreplication.bat" initialize-all "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--bindDN" "%AdminUser-1%" "--bindPassword" "%AdminPwd-1%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-1%

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-2%" "--port" "%AdminPort-2%" "--bindDN" "%AdminUser-2%" "--bindPassword" "%AdminPwd-2%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-2%

The other two reported problem also seems to be related, I mean all these 3 behavior is seen when replication is enabled between OpenDJ which are in different Datacenter.

References:
https://github.com/OpenIdentityPlatform/OpenDJ/issues/113
https://github.com/OpenIdentityPlatform/OpenDJ/issues/111


Moreover we have tried using version 4.4.5 also, but we are facing same issues on it too.
