### ISSUE TITLE
Issue while checking the Replication status when Replication is enabled on multiple baseDNs. 

### ISSUE THREAD

**Issue by himanshugawande** [OpenIdentityPlatform/OpenDJ#113]
**Describe the bug**
In my OpenDj I have configured more than one BaseDN and when I enable "Replication" for atleast one baseDN and then when I try to check the Replication status using the following script sometimes it shows the below provided error. This is inconsistent. It works 2 out of 4 attempts though.

Script :
D:\Apps\opendj\bat>dsreplication.bat status "--trustAll" "--no-prompt" -h "ap-prod-server-1" -p "4444" --adminUID "OpenDjAdmin" --adminPassword "*****@1234"

Error :
Could not connect to ap-prod-server-1:4444. Check that the server is running
and that it is accessible from the local machine.  Details: Connect Error: The
connection attempt to server ap-prod-server-1/10.220.31.11:4444 has failed
because the connection timeout period of 30000 ms was exceeded

**To Reproduce**
1. Add atleast two baseDn's in the DS.
2. Enable Replication for anyone of it.
3. Now run the provided script. 

**Expected behavior**
It must successfully show the proper status of Replication.

**Screenshots**

![image](https://user-images.githubusercontent.com/60377982/78755343-9a5c0a80-7996-11ea-80bf-c94365628130.png)

**Desktop (please complete the following information):**

Server OS: Microsoft 2012R2 / 2016
Java: Same behaviour with jdk1.8.0.144 / jre1.8.0.144 / jdk11.0.1 / 13.0.2
OpenDJ version : Same behaviour with 4.4.1 & 4.4.5
Replication: Multimaster Synchronization

**Additional context**
Infra is on AWS.
Firewall is disabled.

**Comment by vharseko** [comment]
can't reproduce the problems as described

**Comment by himanshugawande** [comment]
The issue is reproducible and has been reported by our customer as well. So it is not one of a case or infraspecific. 
Here is a couple of more pointers that might help.

The issue is only seen when the 2 instances are in a different data center. For example (1 OpenDJ instance is in ap-south-1a and 2nd one is on ap-south-1b).

In my on-premise network within my LAN, I have one data center, I am unable to reproduce the issue in this case. But we are able to replicate on AWS.

The customer has 2 setups, dev, and production. The dev setup is within the datacenter and the issue is not seen. But for prod setup which are is different datacenter, the issue is observed.

Also, we are customizing the schema, not sure if that is related.

We are also enabling the replication using the below scripts.

"%OpenDJHome%\bat\dsreplication.bat" enable "--trustAll" "--noPropertiesFile" "--no-prompt" "--host1" "%LDAPServer-1%" "--port1" "%AdminPort-1%" "--bindDN1" "%AdminUser-1%" "--bindPassword1" "%AdminPwd-1%" "--replicationPort1" "%ReplPort-1%" "--host2" "%LDAPServer-2%" "--port2" "%AdminPort-2%" "--bindDN2" "%AdminUser-2%" "--bindPassword2" "%AdminPwd-2%" "--replicationPort2" "%ReplPort-2%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsreplication.bat" initialize-all "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--bindDN" "%AdminUser-1%" "--bindPassword" "%AdminPwd-1%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-1%

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-2%" "--port" "%AdminPort-2%" "--bindDN" "%AdminUser-2%" "--bindPassword" "%AdminPwd-2%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-2%

The other two reported problem also seems to be related, I mean all these 3 behavior is seen when replication is enabled between OpenDJ which are in different Datacenter.

References:
https://github.com/OpenIdentityPlatform/OpenDJ/issues/113
https://github.com/OpenIdentityPlatform/OpenDJ/issues/111


Moreover we have tried using version 4.4.5 also, but we are facing same issues on it too.

**Comment by himanshugawande** [comment]
The issue is reproducible and has been reported by our customer as well. So it is not one of a case or infraspecific. 
Here is a couple of more pointers that might help.

The issue is only seen when the 2 instances are in a different data center. For example (1 OpenDJ instance is in ap-south-1a and 2nd one is on ap-south-1b).

In my on-premise network within my LAN, I have one data center, I am unable to reproduce the issue in this case. But we are able to replicate on AWS.

The customer has 2 setups, dev, and production. The dev setup is within the datacenter and the issue is not seen. But for prod setup which are is different datacenter, the issue is observed.

Also, we are customizing the schema, not sure if that is related.

We are also enabling the replication using the below scripts.

"%OpenDJHome%\bat\dsreplication.bat" enable "--trustAll" "--noPropertiesFile" "--no-prompt" "--host1" "%LDAPServer-1%" "--port1" "%AdminPort-1%" "--bindDN1" "%AdminUser-1%" "--bindPassword1" "%AdminPwd-1%" "--replicationPort1" "%ReplPort-1%" "--host2" "%LDAPServer-2%" "--port2" "%AdminPort-2%" "--bindDN2" "%AdminUser-2%" "--bindPassword2" "%AdminPwd-2%" "--replicationPort2" "%ReplPort-2%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsreplication.bat" initialize-all "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--adminUID" "%GlobalAdminUser%" "--adminPassword" "%GlobalAdminPwd%" "--baseDN" "%Final-BaseDN%"

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-1%" "--port" "%AdminPort-1%" "--bindDN" "%AdminUser-1%" "--bindPassword" "%AdminPwd-1%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-1%

"%OpenDJHome%\bat\dsconfig.bat" set-replication-domain-prop "--trustAll" "--noPropertiesFile" "--no-prompt" "--hostname" "%LDAPServer-2%" "--port" "%AdminPort-2%" "--bindDN" "%AdminUser-2%" "--bindPassword" "%AdminPwd-2%" "--provider-name" "Multimaster Synchronization" "--domain-name" "%Final-BaseDN%" --set source-address:%LDAP_IP-2%

The other two reported problem also seems to be related, I mean all these 3 behavior is seen when replication is enabled between OpenDJ which are in different Datacenter.

References:
https://github.com/OpenIdentityPlatform/OpenDJ/issues/112
https://github.com/OpenIdentityPlatform/OpenDJ/issues/111
