### ISSUE TITLE
A groupOfURLs causes uncaught exception

### ISSUE THREAD

**Issue by juando-martin** [OpenIdentityPlatform/OpenDJ#114]
**Description**
Using groupOfURLs to create group references causes some internal error and the server no longer works. Error messages show uncaught exceptions. The problem occurs when introducing in a groupOfURLs entry a value like:

`memberURL: ldap:///ou=People,dc=example,dc=com??sub?(ismemberof=cn=users,ou=Group,dc=example,dc=com)`

**To reproduce**
1. Install server from scratch using the attached ldif file to populate it
2. Start the control panel
3. Click on Manage Entries
4. Click 'dc=example,dc=com'->'People'->'user.0'
5. See error in attached screenshot (1)
6. Click 'dc=example,dc=com'->'Group'
7. See error in attached screenshot (2)

**Expected behavior**
No error should appear. No error happens if the memberURL is removed from the groupOfURs entry.

**Screenshots**
![Screenshot1](https://user-images.githubusercontent.com/2488826/79555600-28737780-80a0-11ea-967c-8a2f262995fb.png)
![Screenshot2](https://user-images.githubusercontent.com/2488826/79555622-2f9a8580-80a0-11ea-937e-71b1b7f15348.png)

**Desktop**
 - OS: openSUSE Linux 15.1
 - OpenDJ 4.4.5 (tried 4.3.x)
 - Java 11.0.6 (tried also 1.8.0)
[ldifdata.zip](https://github.com/OpenIdentityPlatform/OpenDJ/files/4492137/ldifdata.zip)

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/issues/10#issuecomment-427389189
