### ISSUE TITLE
OpenDJ images are returning hundreds of vulnerabilities in a Clair scan

### ISSUE THREAD

**Issue by Gui13** [OpenIdentityPlatform/OpenDJ#115]
**Describe the bug**

Scanning the latest image of opendj shows lots of vulnerabilities (~640)

**To Reproduce**
1. pull the latest opendj image from docker hub
2. push it to any installation of harbor that scans the container images
3. Verify that the image has lots and lots of vulnerabilities

**Expected behavior**

I would expect a few of the vulnerabilities to be easily plugged by depending on more recent upstream images at least.

The rest might be fixed by upgrading the java version used by opendj, but this is way more work.

**Screenshots**

![image](https://user-images.githubusercontent.com/44523/80113052-156e1500-8582-11ea-97c7-36ab022f5566.png)

Here are the critical ones:
![image](https://user-images.githubusercontent.com/44523/80113989-4733ab80-8583-11ea-82a9-9a1e7c0d973c.png)

**Additional context**

Here is the response from Harbor when querying the scan result of the opendj image:
[clair_report.json.txt](https://github.com/OpenIdentityPlatform/OpenDJ/files/4523290/clair_report.json.txt)

**Comment by Gui13** [comment]
An easy fix is if you depend on `openjdk:8` instead of `java:8` you'll get a WAY more recent version of Java.

The java you are using dates back from 2017: Java 8u111

**Comment by Gui13** [comment]
Hi @varsheko! Thanks for the merge, please note that the alpine version is affected too. 

I don’t exactly know where the java: images come from, but there might be an openjdk:8-alpine to use.

Also, I saw that your travis CI tests the compilation with java11, you could also use the openjdk:11 in this case, they are even more recent/supported.

**Comment by vharseko** [comment]
DJ openjdk:11 compatible
