### ISSUE TITLE
Issue starting control-panel

### ISSUE THREAD

**Issue by fabiandsouza88** [OpenIdentityPlatform/OpenDJ#117]
**Describe the bug**
Control Panel doesnt work as expected through Docker or even if i download the zip file and Install the opendj and then run the Control panel 

**To Reproduce**

a) Through Docker,  

1. docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 --name ldap-01 openidentityplatform/opendj
2. Enter the container , Go to 'opendj/bin'
3. Execute  ./control-panel
4. Gets the following Error "Could not launch Control Panel.  Check that you have access to the display."
5. Assumed as DISPLAY hasnt been set on the Docker container , so might be because of it. 

So now I down the binary and try to install on my local box (Linux Machine Rhel 7)

b) Binary Zip file 
1. Download the 4.4.5 https://github.com/OpenIdentityPlatform/OpenDJ/releases
2. unzip it and than run the ./setup --cli
3. After installation check the status , which shows the opendj is up and running
4. Execute  ./control-panel
5. Gets the following Error "Could not launch Control Panel.  Check that you have access to the display."
6. On my local box , Display has been configured and I can open Xclock as well as xmessage 

**Expected behavior**
Control-Panel should open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Redhat
 - Version 7
- Java Version : openjdk version "1.8.0_242"

**Additional context**
Using the OpenDj version 4.4.5,  

 [centos@universal-messanger0 bin]$ ./control-panel -r
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Could not launch Control Panel.  Check that you have access to the display.
Check file /tmp/opendj-control-panel-2746011568273871827.log for details.

I dont feel its the problem of DISPLAY as xmessage works perfectly fine on the host. I even tried ./control-panel -r -h myhostname -p 4444

Logs under "/tmp/opendj-control-panel-2746011568273871827.log" has following details ie
[28/04/2020:19:41:12 +0200] category=org.opends seq=0 severity=INFO msg=Application launched April 28, 2020 7:41:12 PM CEST
[28/04/2020:19:41:12 +0200] category=org.opends.guitools.controlpanel.ControlPanelLauncher seq=1 severity=WARNING msg=Error launching GUI: java.awt.HeadlessException
[28/04/2020:19:41:12 +0200] category=org.opends.guitools.controlpanel.ControlPanelLauncher seq=2 severity=WARNING msg=java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
java.awt.Window.<init>(Window.java:536)
java.awt.Frame.<init>(Frame.java:420)
java.awt.Frame.<init>(Frame.java:385)
org.opends.quicksetup.SplashScreen.<init>(SplashScreen.java:89)
org.opends.guitools.controlpanel.ControlPanelSplashScreen.<init>(ControlPanelLauncher.java:267)
org.opends.guitools.controlpanel.ControlPanelSplashScreen.main(ControlPanelLauncher.java:282)
org.opends.guitools.controlpanel.ControlPanelLauncher$1.run(ControlPanelLauncher.java:174)
java.lang.Thread.run(Thread.java:748)

Can you 'all please suggest me how can i start control-panel. As updated earlier, its not an issue with Display or X11 as I can open xclock and xmessage from my terminal.

**Comment by fabiandsouza88** [comment]
Got fixed after chnaging the Java version

https://www.oracle.com/technical-resources/articles/javase/headless.html
https://github.com/chatty/chatty/issues/261

**Comment by imShakil** [comment]
I had to install `deafult-jre` instead of `default-jre-headless`.

OS: Ubuntu 22
OpenDJ: 4.6.5
