### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by InterstellarScout** [OpenIdentityPlatform/OpenDJ#120]
**Describe the bug**
Documentation in the Getting Started guide talks about how the Java Environment should be set up. The link provided is broken and leads to a dead end. Additionally, the documentation provides no details on how the java environment needs to be set up. 

We need details on what the current Java environment should look like. 

**To Prepare For Installation**
Make sure you have a required Java environment installed as described in [Java Environment.](https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Java-Environment)

**To Reproduce**
Go to [Installation-Guide](https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide) and see the broken link below. 

**Expected behavior**
Bring you to a page with information on the java environment.

**Comment by kurnysh** [comment]
done
