### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by InterstellarScout** [OpenIdentityPlatform/OpenDJ#123]
**Describe the bug**
Every time something is run in a installed instance of OpenDJ, I get the following issue:
[root@ip-172-31-81-250 bin]# ./status
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Given that error, when my base dn failed to generate, no logs were presented in the supplied logs. 

**To Reproduce**
Install a fresh version of OpenDJ onto CentOS or Amazon Linux2 EC2 Instance. Install java 1.8.0
specifically java-1.8.0-openjdk
Install the server in any configuration, then run a status script. 

**Expected behavior**
Logs should generate and no warning message can be presented. 

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 

**Additional context**
Upon some research this has come up:
http://www.slf4j.org/codes.html#StaticLoggerBinder
Showing that there is a missing file. StaticLoggerBinder is dated and unsupported so should it be included with OpenDJ's installation? Otherwise, how do I add this class (https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.6.2/slf4j-simple-1.6.2.jar) to the ClassPath for OpenDJ to use for logging?

The biggest reason why I ask this is because when there is a critical issue that ends my task, say attempting to LDAPSearch but the bindDN doesn't exist after initial setup, it outputs a log that _should_ have information in it
`
See /tmp/opendj-setup-5112575948393152809.log for a detailed log of the failed
operation.
`
The above file would be empty. I have no way to troubleshoot as far as I know. 
Any Advise?

**Comment by mario-ragucci-sp** [comment]
+1
Experiencing the very same issue and cannot even debug it, since the logfile always stays empty.
For OpenDJ being a stable product for quite some time, I am experiencing too many issues lately to still be confident running this software without proper logging functionality.

**Comment by InterstellarScout** [comment]
@vharseko Hello! Thank you for that fix. How do I apply it to our instance?
