### ISSUE TITLE
Docker: Default path as environment variable to import ldif

### ISSUE THREAD

**Issue by fabiandsouza88** [OpenIdentityPlatform/OpenDJ#130]
**Is your feature request related to a problem? Please describe.**
-- Default path in docker image container so that when ever we can upload the ldif files to this mount point , they get automatically imported.
 
I am new to opendj and I have started using your opendj docker image.
Currently I am using docker-compose to create my services. Once my services gets started , I have to manually login the docker container or run docker exec command import-ldif to import my ldif file  to the container. Instead i feel the suggestion I have requested, would be more helpful .
Not sure if there is any other good approach. 
Why i m using docker services because i have swarmed my services across 3 nodes.

**Describe the solution you'd like**
Environment Variable like  Import_path so that whenever we mount the ldif files to this location, these ldif files are automatically imported on startup of the container.
 
**Describe alternatives you've considered**
To automate this manual task, i have created a script which runs automatically from outside the container when ever it finds the services are up and running (Didnt like this workaround)

**Comment by maximthomas** [comment]
@fabiandsouza88 
Hello, you can run the following command to run import-ldif from your machine. Of course, this is just an example and you should use your values

```bash
docker run -it --rm --entrypoint "/opt/opendj/bin/import-ldif" \
   -v ./data.ldif:/opt/opendj/import-data/data.ldif \
   openidentityplatform/opendj \
  -b dc=openam,dc=openidentityplatform,dc=org  -D 'cn=Directory Manager' -h opendj -p 1389 -w passw0rd -l /opt/opendj/import-data/data.lidf
```

**Comment by vharseko** [comment]
updated https://hub.docker.com/repository/docker/openidentityplatform/opendj

**Comment by fabiandsouza88** [comment]
Thank you @maximthomas ,Currently im doing something similar ie  using a run command from outside the docker container to import my file.  Since i am using a compose file  as below, this becomes a 2 step process, ie 1st to start the service and 2nd to execute the import 

version: '3.7'
services:
  dbl:
    networks:
      - opendj-network
    environment:
      ROOT_PASSWORD: ${PASSWORD}
    image: ${OPENDJ_REPOSITORY}:${OPENDJ_VERSION}
    volumes:
      - type: volume
        source: dbl
        target: /opt/opendj/import-data/
    ports:
      - target: 4444
        published: 2444
        protocol: tcp
        mode: host
      - target: 1389
        published: 2389
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != ${DOCKER_NODE0}
volumes:
  dbl:

My Feature request was, if some one uploads ldif files to some default location example /opt/opendj/import-data/ , than the when ever the container is started it should pick up the ldif file automatically from /opt/opendj/import-data/ and there shouldnt be a need to run the import-ldif command explicitly.

**Comment by maximthomas** [comment]
@fabiandsouza88 
you can add or mount files to /opt/opendj/bootstrap/data/ and opendj will load them during startup, see https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-packages/opendj-docker/bootstrap/setup.sh#L31

**Comment by fabiandsouza88** [comment]
@maximthomas Thank you , It works as expected :)
