### ISSUE TITLE
Updating OpenDJ

### ISSUE THREAD

**Issue by yuppox** [OpenIdentityPlatform/OpenDJ#132]
I started my OpenDJ server with a self-signed certificate.

How can I update that to a signed one?

Also, I'm considering moving to the official Docker app, instead of the manual installation I have. Are there any issues exporting/importing the data, if I do so?

Thanks!

**Comment by TeaM-TL** [comment]
keytool wil be your friend ;-) more here:
https://backstage.forgerock.com/docs/opendj/3.5/admin-guide/#chap-change-certs

**Comment by vharseko** [comment]
thanks @TeaM-TL
