### ISSUE TITLE
Replication status attributes for schema backend not read from disk

### ISSUE THREAD

**Issue by jpn-e** [OpenIdentityPlatform/OpenDJ#140]
**Describe the bug**
The various ds-sync-* attributes for the replication state are set as part of replication and stored by the schema backend to 99-user.ldif, but they are not properly read back from disk when starting up.
As a result the cursor for replication replay will not be setup properly based on what changes have already been replayed, and an attempt to replay the entire available change history will happen on each startup.

Normally this does not cause any visible problems, it is just unnecessary, but it can be troublesome in combination with issue #139 as every schema change is a modification.

**To Reproduce**
The problem can be reproduced by restarting an OpenDJ instance where replication is configured.

**Expected behavior**
Schema replication should continue from the last applied change, not try to re-apply all available changes on restart of OpenDJ.

**Comment by jpn-e** [comment]
I made a quick patch [Add-ds-sync-attributes-from-schema-ldif-to-extaAttr.patch](https://gist.github.com/jpn-e/9e117bb0364ddd185d6a2e02ec27008b) to load the attributes set/used by replication.
This is mostly a test to see that the values are sent to the RS and the replication cursor is setup properly when the attributes are loaded from 99-user.ldif.
I don't like the fixed list of attributes to add to extraAttributes that this uses, it should probably be integrated more with the actual schema loading so that all attributes that are not actually part of the schema itself are loaded into extraAttributes.

**Comment by vharseko** [comment]
thanks for patch, please make pull request
