### ISSUE TITLE
Replication not catching up properly if there is many pending changes

### ISSUE THREAD

**Issue by jpn-e** [OpenIdentityPlatform/OpenDJ#141]
**Describe the bug**
When a DS is too far behind the pending changes will be read in chunks into lateQueue, maximum 100 changes or a maximum size at a time.
Refilling lateQueue does not work properly, so if the server is behind with more than 100 changes (or exceeding the size limit) it will not catch up properly.

**To Reproduce**
In a system with two replicated servers
1. Stop server 2
2. Make more than 100 changes (add/delete/modify) on server 1
3. Start server 2
4. Check the replication status and see that server 2 only applies up to 100 changes

It may be possible to get server 2 to catch up by restarting it after it is done processing the chunk, so that it takes another chunk on the next startup.

**Comment by jpn-e** [comment]
To workaround this problem we have been using a  [patch to attempt to re-fill lateQueue instead of assuming catch-up is done when its empty](https://gist.github.com/jpn-e/6a36e36a140ea4458c78faa46b8589b8).

This is still a bit fragile and just glued on top of the current lateQueue/msgQueue handling, but seems to work OK.
For a proper solution the lateQueue/msgQueue handling would probably have to be reworked.

**Comment by vharseko** [comment]
thanks for patch, please make pull request

**Comment by vharseko** [comment]
@jpn-e what do you think about this commit https://github.com/WrenSecurity/wrends/commit/ebebdacc84d94a73cc42a6a995a43006870985c6 ?
