### ISSUE TITLE
Connection issues towards one RS may prevent others from working properly

### ISSUE THREAD

**Issue by jpn-e** [OpenIdentityPlatform/OpenDJ#143]
**Describe the bug**
Replication servers will try to establish connections to other replication servers in the topology to which it is does not already have a connection, it will also handle incoming connections from other RS or DS.
This is done in different threads but synchronized so that only one of those things are happening at once, so 
somewhat simplified we can see it as a loop consisting of
1. Try to establish connections to other RS:es in the topology
2. Accept pending incoming connections from other RS and DS

The problem as we have observed it is that network issues causing outgoing connections to fail slow (e.g. null-routed traffic or dropping network element) may cause enough delay that when the RS get back to checking for incoming connections they have all timed out.
This looks like SSL handshake errors in the logs, but is not (in our case) due to certificate problems but simply due to the connecting party having given up.

This can repeat for a significant amount of time, preventing connections between otherwise healthy RS and DS.
- Try to establish outgoing connections - slow failure
- Accept incoming connections - all have timed out
- Try again to establish outgoing connections - slow failure
- Accept incoming connections (all have timed out)
- ...

**To Reproduce**
This can easiest be reproduced by setting up a replication topology with three (combined RS/DS) servers, intentionally setup up a firewall to drop (not reject) all traffic to/from one of them and then restarting them all.
Often the the two servers that should be able to connect to other will not be able to accept each other's connections in time since they are busy trying to connect to the unreachable third  server.

**Expected behavior**
One misbehaving server/network problems towards one server should not prevent the others from working.

**Comment by jpn-e** [comment]
The break the timeout cycle we have been using a patch to exclude unresponsive servers for a few cycles, this seems to be working.
[
Blacklist-misbehaving-servers-for-a-little-bit.patch
](https://gist.github.com/jpn-e/c8b542baad4a54d8170efd62f6853202)

**Comment by vharseko** [comment]
Thanks, please make PR https://github.com/OpenIdentityPlatform/OpenDJ/pulls <https://github.com/OpenIdentityPlatform/OpenDJ/pulls>

**Comment by vharseko** [comment]
thanks https://github.com/OpenIdentityPlatform/OpenDJ/pull/144/commits/6b8171ce78514e2a15bc825b2944b31ac5e4c024
