### ISSUE TITLE
Version 4.4.7 Error Edit java.properties

### ISSUE THREAD

**Issue by jack0623** [OpenIdentityPlatform/OpenDJ#145]
**Describe the bug**
When I edit  OpenDJX.X.X\config\java.properties to add some parameter the opendj instance crash and give that error when I tray to start again s
`C:\.....\OpenDJ\bat\start-ds.bat
The syntax of the command is incorrect.`
Also I saw than the dsjavaproperties did not exist.
 

**To Reproduce**
1. Go to ....\OpenDJ\config\
2. Edit the java.properties
3. Replace the line 
start-ds.java-args="-Xms3072m" "-Xmx3072m" 
By 
start-ds.java-args="-Xms3072m" "-Xmx3072m" "-d64" "-XX:+UseConcMarkSweepGC" "-XX:+UseCompressedOops" "-XX:MaxTenuringThreshold=1" "-XX:NewSize=1024m" "-XX:MaxNewSize=1024m"
In order to improve the performance as OpenDJ 3.0 (My old OpenDJ)
4. Restart the server and the server did no start again and send this messages
`C:\.....\OpenDJ\bat\start-ds.bat
The syntax of the command is incorrect.` 
*** I can not  compile because I don't have dsjavaproperties.bat

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Java: 
> openjdk version "1.8.0_262"
> OpenJDK Runtime Environment (Zulu 8.48.0.52-SA-win64) (build 1.8.0_262-b19)
> OpenJDK 64-Bit Server VM (Zulu 8.48.0.52-SA-win64) (build 25.262-b19, mixed mode)

 - Version OpenDJ-4.4.7

**Comment by maximthomas** [comment]
@jack0623 thank you for the issue. Please create pull request.

**Comment by vharseko** [comment]
please try without quotes:
```
start-ds.java-args=-Xms3072m -Xmx3072m -d64 -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:MaxTenuringThreshold=1 -XX:NewSize=1024m -XX:MaxNewSize=1024m
```
