### ISSUE TITLE
TLS handshake unlimited timeout?

### ISSUE THREAD

**Issue by Ykrad** [OpenIdentityPlatform/OpenDJ#146]
**Describe the bug**
OpenDJ waits on TLS handshake data from a client forever if the client is unable to respond to the handshake (due to out of memory, out of pids etc). We can see that the epoll_wait syscall timeout is set to -1 so we think this is set from OpenDJ or Grizzly.

This waiting on handshake blocks the server from performing normally.

**To Reproduce**
1. Setup a server. 
2. Then connect to that server using TLS with a client that will fail to respond. We managed this using cgcreate and cgexec from the libcgroup-tools package to set a "sweetspot" where the client could start but could not respond.
3. Take a jstack of the server process
4. See that selector threads are stuck in the jstack output. Example:
"OpenDJ LDAP SDK Grizzly selector thread(5) SelectorRunner" #147 daemon prio=5 os_prio=0 tid=0x00007facd9f0d000 nid=0x15a5 runnable [0x00007face3af8000]
   java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
    at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    - locked <0x000000078a5b1888> (a sun.nio.ch.Util$3)
    - locked <0x000000078a5b1878> (a java.util.Collections$UnmodifiableSet)
    - locked <0x000000078a5b1650> (a sun.nio.ch.EPollSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97) 

**Expected behavior**
Server should not enter a blocked state due to TLS handshake. At least a way to configure the TLS handshake timeout would be prudent (if there already is a way please let me know, I can't find it). 

**Desktop (please complete the following information):**
 - OS: RHEL 7

**Additional context**
We are running OpenDJ v4.2.5. The issue was discovered when a client ran out of process IDs.

If this has already been fixed in a later version of OpenDJ please let me know.

**Comment by Ykrad** [comment]
Hi,

After some more troubleshooting we found that the handshake timeout can be set in SSLBaseFilter from Grizzly: https://github.com/javaee/grizzly/blob/master/modules/grizzly/src/main/java/org/glassfish/grizzly/ssl/SSLBaseFilter.java#L210

JavaDoc of the setter:
/**
 * Sets the handshake timeout.
 * @param handshakeTimeout timeout value, or <code>-1</code> means for
 * non-blocking handshake mode.
 * @param timeUnit {@link TimeUnit}
 */

We tested setting this value in OpenDJ accordingly and it solves the issue:
--- opendj-grizzly/src/main/java/org/forgerock/opendj/grizzly/GrizzlyLDAPConnection.java
+++ opendj-grizzly/src/main/java/org/forgerock/opendj/grizzly/GrizzlyLDAPConnection.java
@@ -821,6 +821,7 @@ final class GrizzlyLDAPConnection implements LDAPConnectionImpl, TimeoutEventLis
             sslEngineConfigurator.setEnabledCipherSuites(cipherSuites.isEmpty() ? null : cipherSuites
                     .toArray(new String[cipherSuites.size()]));
             final SSLFilter sslFilter = new SSLFilter(DUMMY_SSL_ENGINE_CONFIGURATOR, sslEngineConfigurator);
+            sslFilter.setHandshakeTimeout(10000, TimeUnit.MILLISECONDS);
             installFilter(sslFilter);
             sslFilter.handshake(connection, completionHandler);
         }
 
--- opendj-grizzly/src/main/java/org/forgerock/opendj/grizzly/LDAPServerFilter.java
+++ opendj-grizzly/src/main/java/org/forgerock/opendj/grizzly/LDAPServerFilter.java
@@ -28,6 +28,7 @@ import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.CancellationException;
+import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong; 
import javax.net.ssl.SSLEngine;
@@ -384,7 +385,9 @@ public final class LDAPServerFilter extends BaseFilter {
                     return false;
                 }
                 SSLUtils.setSSLEngine(connection, sslEngine);
-                installFilter(startTls ? new StartTLSFilter(new SSLFilter()) : new SSLFilter());
+                SSLFilter sslFilter = new SSLFilter();
+                sslFilter.setHandshakeTimeout(10000, TimeUnit.MILLISECONDS);
+                installFilter(startTls ? new StartTLSFilter(sslFilter) : sslFilter);
                 return true;
             }
         }

The questions that now remains is if going from non-blocking to blocking handshake mode has any wider implications and if this should be fixed in OpenDJ or Grizzly?

Br

**Comment by Ykrad** [comment]
It seems that the SSLBaseFilter class has not been updated since [2012](https://github.com/javaee/grizzly/commit/9569bd64fcd7e92f65db0a226605d654407dbf85) so I would assume that requesting a change in Grizzly would be hard.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/pull/149
