### ISSUE TITLE
OpenDJ 4.4.7 "Error Reading Configuration" on OpenDJ control panel.

### ISSUE THREAD

**Issue by jaineshsingh** [OpenIdentityPlatform/OpenDJ#148]
**Describe the bug**
Error Message "Error Reading Configuration" is displayed on the control panel of OpenDJ 4.4.7 when a new user is added to the OpenDJ and it is under replication. 

**To Reproduce**
1. Two OpenDJ server A1 and A2 are running in replication mode. 
2. User is added in one of the OpenDJ server.
3. Trying to login with the newly added user in our custom repository.
4. "Error Reading Configuration" message is displayed on both the OpenDj servers control panel.

**Expected behavior**
Error message should not be displayed  on the control panel.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23317140/100082288-12b40500-2e6e-11eb-83ea-ca9535d03726.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 2012

**Comment by vharseko** [comment]
fixed [4.6.5](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.6.5)
