### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by cruelbardak** [OpenIdentityPlatform/OpenDJ#150]
after installed and setup many JRE environments  

openjdk16 
JDK11 - oracle

i´m unable to obtain TLS 1.3 support, this is my "ldapsearch --port 389 --baseDN "" --searchScope base "(objectclass=*)" supportedTLSCiphers supportedTLSProtocols"  

command with openjdk16: (just last 6 lines)
supportedTLSCiphers: TLS_RSA_WITH_AES_128_CBC_SHA256
supportedTLSCiphers: TLS_RSA_WITH_AES_128_GCM_SHA256
supportedTLSCiphers: TLS_RSA_WITH_AES_256_CBC_SHA
supportedTLSCiphers: TLS_RSA_WITH_AES_256_CBC_SHA256
supportedTLSCiphers: TLS_RSA_WITH_AES_256_GCM_SHA384
supportedTLSProtocols: TLSv1.2

output with oracle jdk 11  (just last 8 lines):
supportedTLSCiphers: TLS_RSA_WITH_AES_128_GCM_SHA256
supportedTLSCiphers: TLS_RSA_WITH_AES_256_CBC_SHA
supportedTLSCiphers: TLS_RSA_WITH_AES_256_CBC_SHA256
supportedTLSCiphers: TLS_RSA_WITH_AES_256_GCM_SHA384
supportedTLSProtocols: SSLv2Hello
supportedTLSProtocols: TLSv1
supportedTLSProtocols: TLSv1.1
supportedTLSProtocols: TLSv1.2

TLS 1.3 is currently supported ? or is necessary some extra configuration steps ?

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.5.5
