### ISSUE TITLE
Unable to run the docker image by importing the ldif

### ISSUE THREAD

**Issue by sulog** [OpenIdentityPlatform/OpenDJ#151]
When I am running the below command

docker run -it --rm --entrypoint "/opt/opendj/bin/import-ldif" -v ./data.ldif:/opt/opendj/import-data/data.ldif openidentityplatform/opendj -b dc=example,dc=com -D "cn=Directory Manager" -h ldap-01.domain.com -p 1389 -w Password -l /opt/opendj/import-data/data.lidf

getting the error as mentioned below,

The local instance is not configured or you do not have permissions to access
it.

Could someone help me on this.

**Comment by maximthomas** [comment]
Hello @sulog 
To import a `ldif` file with initial data, you should mount a directory with the file to `/opt/opendj/bootstrap/data/` in a docker image. OpenDJ will load this file after initialization.
