### ISSUE TITLE
Extra quotes in setup.bat break it

### ISSUE THREAD

**Issue by danmoseley** [OpenIdentityPlatform/OpenDJ#155]
**Describe the bug**
Script error when running setup.bat.

**To Reproduce**
1. Install the 4.4.9 MSI on Windows 10
2. In an admin prompt, navigate to `C:\Program Files (x86)\OpenDJ`
3. Run `setup` (the parameters don't matter)
4. It fails with `\OpenDJ\.\config\java.properties""' was unexpected at this time.`

**Expected behavior**
It completes setup.

By commenting out `@echo off` in the batch files I see the output end thus:
```
C:\Program Files (x86)\OpenDJ>set JAVA_PROPERTIES="C:\Program Files (x86)\OpenDJ\.\config\java.properties"

C:\Program Files (x86)\OpenDJ>if not exist "C:\Program Files (x86)\OpenDJ\.\config\java.properties" goto:eof

C:\Program Files (x86)\OpenDJ>set CMD="findstr /b [^#]*setup.java-args=.* "C:\Program Files (x86)\OpenDJ\.\config\java.properties""
\OpenDJ\.\config\java.properties""' was unexpected at this time.

C:\Program Files (x86)\OpenDJ>for /f "tokens=2 delims==" %a in ( '"findstr /b [^#]*setup.java-args=.* "C:\Program Files (x86)\OpenDJ\.\config\java.properties""' ) do set PROPERTY_VALUE=%a

C:\Program Files (x86)\OpenDJ>
```
The bug seems to be the double quotes on this line. Removing them gets past this problem.
https://github.com/OpenIdentityPlatform/OpenDJ/blob/4b64543c12cfc61571f6fcb9af2d4a510283e20b/opendj-server-legacy/resource/bin/_script-util.bat#L232

As far as I know there's nothing unusual about my setup.

**Comment by danmosemsft** [comment]
I would offer a PR but I see this file hasn't changed in years so perhaps I'm missing something.

Also, although this makes setup complete, it didn't register or start the service so ultimately I've not been successful.

**Comment by maximthomas** [comment]
@danmoseley Hello, I could not reproduce the issue. Setup execuded without any errors on on clean windows 10 and AdoptOpenJDK 11
Setting JAVA_PROPERTIES without quotes could cause path error. May be there is an issue with your environment variables?

**Comment by danmoseley** [comment]
@maximthomas Hmm, not sure. If and when I try this again, I'll reopen if I see it then and investigate further.

**Comment by danmoseley** [comment]
I ended up using the docker image, BTW, since it's so much easier. Thanks for looking!
