### ISSUE TITLE
SSL and Docker

### ISSUE THREAD

**Issue by audouts** [OpenIdentityPlatform/OpenDJ#156]
**Is your feature request related to a problem? Please describe.**
It's easy to start a Docker container with OpenDJ but only with a self-signed certificate. I can't find good documentation on how to use that in conjunction with a server where I have a valid SSL certificate.

A related problem is that the Wiki references this, several times:
_Preparing For Secure Communications_
but the link is a dead-end.

**Describe the solution you'd like**
I would like two things:
1. Complete documentation on setting up SSL (including fixing those broken links)
2. An example/how-to for installing an SSL certificate with Docker

**Describe alternatives you've considered**
I am considering a normal install or a Docker install.

**Additional context**
I use certbot for SSL cert. renewal. Is there a way to integrate that, perhaps?

**Comment by nnadams** [comment]
I got this to work recently. There doesn't seem to be a way to just provide the cert/key, but you can premake a pkcs12 store.

Take a look at the table in [opendj-packages/opendj-docker/README.md](https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-packages/opendj-docker/README.md) in this repo. You can replace the `OPENDJ_SSL_OPTIONS` environment variable to use a password protected pkcs12 store. I created a opendj.pfx store with my exisiting certs and mounted that file in the container.

I created the store with this command. You'll be asked to enter a password for the .pfx file.
`openssl pkcs12 -export -out opendj.pfx -inkey private.key -in server.crt -certfile cachain.crt`

Then when you run the container just set this environment variable with the pfx path and the password.
`OPENDJ_SSL_OPTIONS="--usePkcs12keyStore /data/opendj.pfx --keyStorePassword PASSWORD"`

**Comment by maximthomas** [comment]
@audouts fixed links in the [Installation Guide](https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide)

**Comment by maximthomas** [comment]
@nnadams thank you for the hint!
I'll add it to [How To](https://github.com/OpenIdentityPlatform/OpenDJ/wiki/How-To) article in the wiki

**Comment by audouts** [comment]
Thank you!
