### ISSUE TITLE
Able to create multiple groups with same gidNumber

### ISSUE THREAD

**Issue by Vaseem88** [OpenIdentityPlatform/OpenDJ#163]
In OpenDj LDAP server, I am able to create multiple groups with different group names using the same gidNumber. If I can create several groups with same gidNumber then how it is possible to identify a group using the gidNumber from remote hosts

From the remote host, while sharing a drive we can see the folder properties and get only the group id (gidNumber). So if multiple groups have same gidNumber then how one can possible identify which group have access to that folder?

1. Open the openDJ LDAP server
2. Go to any OU
3. Add a group with a gidNumber
4. Add another group with same gidNumer
5. Verify that the two newly created different groups have the same gidNumber

**Expected behavior**
each group/ user should be unique and should have their own unique id.
the unique id for a group is gidNumer and it always should be unique

**Screenshots**
![image](https://user-images.githubusercontent.com/23305215/110308621-5d751980-8026-11eb-8ad5-3ee70609c930.png)
![image](https://user-images.githubusercontent.com/23305215/110308690-71208000-8026-11eb-9ee1-bd8883e558f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
In a OpenDJ LDAP server, what is actual unique identifier of an object apart from distinguished name, I think it should be the gidNumber for a group and uidNumber for a user. Please correct me if I am wrong.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Administration-Value-Uniqueness
