### ISSUE TITLE
Error Change password via control-panel 

### ISSUE THREAD

**Issue by arulmurugansubramaniam** [OpenIdentityPlatform/OpenDJ#167]
**Describe the bug**
we have imported the exiting users from OpenDS 2.2 to Open DJ 4.4.8(newly installed) through export-ldif  and import-ldif command utility. once after that when we reset the password for a user via control-panel, password was successfully updated in LDAP, But control panel screen throws error "Error updating user password". This is happening sometime only, But some time it shows successful message "User Password Updated"

**To Reproduce**
1. Open 'opendj/bat/control-panel.bat'
2. Click on 'manage entries' under "Directory Data"
3. select "Base Dn"
3. select a user entry, I have selected a user "DFCC"
4. enter "user password" and password (confirm)
5. click "save" button
6. shows "Error updating user password"

**Expected behavior**
Password change successful screen will pop-up

**Screenshots**
<img width="423" alt="change_password_error" src="https://user-images.githubusercontent.com/81243394/112157937-b4294880-8c0d-11eb-97aa-4707f0cd9c11.png">

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Open DJ server control panel]
 - Version [open DJ 4.4.8]

**Additional context**

**Ppen DJ logs**
### opendj/logs/access
[23/Mar/2021:19:23:24 +0530] ABANDON REQ conn=289 op=38 msgID=39 idToAbandon=38
[23/Mar/2021:19:23:24 +0530] ABANDON RES conn=289 op=38 msgID=39 result=119 etime=0
[23/Mar/2021:19:23:24 +0530] EXTENDED REQ conn=289 op=39 msgID=40 name="Password Modify" oid="1.3.6.1.4.1.4203.1.11.1"
[23/Mar/2021:19:23:24 +0530] EXTENDED RES conn=289 op=39 msgID=40 result=0 etime=2
[23/Mar/2021:19:23:24 +0530] SEARCH REQ conn=289 op=37 msgID=38 base="cn=DFCC,ou=people,o=eFunds" scope=base filter="(|(objectClass=*)(objectclass=ldapsubent
ry))" attrs="ds-cfg-alternate-bind-dn"
[23/Mar/2021:19:23:24 +0530] SEARCH RES conn=289 op=37 msgID=38 result=0 nentries=1 etime=1

### opendj/logs/ldap-access.audit.json
{"eventName":"DJ-LDAP","client":{"ip":"172.26.49.110","port":65143},"server":{"ip":"172.26.49.121","port":1389},"request":{"protocol":"LDAP","operation":"SEARCH","connId":289,"msgId":38,"dn":"cn=DFCC,ou=people,o=eFunds","scope":"base","filter":"(|(objectClass=*)(objectclass=ldapsubentry))","attrs":["ds-cfg-alternate-bind-dn"]},"transactionId":"0","response":{"status":"SUCCESSFUL","statusCode":"0","elapsedTime":1,"elapsedTimeUnits":"MILLISECONDS","nentries":1},"timestamp":"2021-03-23T13:53:24.264Z","_id":"9b454ca2-9089-4e88-9725-4009025a0433-118859"}
{"eventName":"DJ-LDAP","client":{"ip":"172.26.49.110","port":65143},"server":{"ip":"172.26.49.121","port":1389},"request":{"protocol":"LDAP","operation":"ABANDON","connId":289,"msgId":39,"idToAbandon":38},"transactionId":"0","response":{"status":"FAILED","statusCode":"119","elapsedTime":0,"elapsedTimeUnits":"MILLISECONDS"},"timestamp":"2021-03-23T13:53:24.264Z","_id":"9b454ca2-9089-4e88-9725-4009025a0433-118861"}
{"eventName":"DJ-LDAP","client":{"ip":"172.26.49.110","port":65143},"server":{"ip":"172.26.49.121","port":1389},"request":{"protocol":"LDAP","operation":"EXTENDED","connId":289,"msgId":40,"name":"Password Modify","oid":"1.3.6.1.4.1.4203.1.11.1"},"transactionId":"0","response":{"status":"SUCCESSFUL","statusCode":"0","elapsedTime":2,"elapsedTimeUnits":"MILLISECONDS"},"timestamp":"2021-03-23T13:53:24.273Z","_id":"9b454ca2-9089-4e88-9725-4009025a0433-118863"}

**Comment by vharseko** [comment]
fixed [4.6.5](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.6.5)
