### ISSUE TITLE
Group types and isMemberOf

### ISSUE THREAD

**Issue by audouts** [OpenIdentityPlatform/OpenDJ#169]
Hi,

I'm having trouble retrieving members of posix groups.

First, assuming this is a valid base, containing users:
`base: ou=people,dc=example,dc=com`

If I apply a filter for a _groupOfUniqueNames_:
```
filter: (&(objectclass=person)(isMemberOf=cn=uniqueGroup,ou=groups1,dc=example,dc=com))
```
the search return a list of members for uniqueGroup.

However, using a _posixGroup_:
```
filter: (&(objectclass=person)(isMemberOf=cn=posixGroup,ou=groups2,dc=example,dc=com))
```
returns empty.

How can I get this to work with posix groups? What groups does _isMemberOf_ work on?

**Comment by audouts** [comment]
I figured out that I can get the _memberUids_ from the group, rather than filtering "people", as I do with _groupOfUniqueNames_.

**Comment by audouts** [comment]
Actually, I would still like to understand why _isMemberOf_ didn't work with a posixGroup, if anyone can help.

**Comment by chenss-1** [comment]
You can fix objectAttribute in config/schema/04-rfc2307bis.ldif ,change posixGroup type to structural. and add cn to MUST
example:
```
objectClasses: ( 1.3.6.1.1.1.2.2 NAME 'posixGroup' SUP top STRUCTURAL
  DESC 'Abstraction of a group of accounts' MUST  ( cn $ gidNumber )
  MAY ( authPassword $ userPassword $ memberUid $ description )
  X-ORIGIN 'draft-howard-rfc2307bis' )
```

**Comment by vharseko** [comment]
try
```
filter: (&(objectclass=person)(memberOf=cn=uniqueGroup,ou=groups1,dc=example,dc=com))
```
https://github.com/OpenIdentityPlatform/OpenDJ/issues/10
