### ISSUE TITLE
how to maintain data persistence?

### ISSUE THREAD

**Issue by Sergey1838** [OpenIdentityPlatform/OpenDJ#171]
I want to keep data/schema modifications persistent. I was looking for the answer everywhere, but couldn't find anything. I assume I have to map volumes. Could you give me some guidance?

**Comment by vharseko** [comment]
use mount folder /opt/opendj/data
```bash
docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 --name ldap-01 openidentityplatform/opendj -v /volumes/openidentityplatform/data:/opt/opendj/data
```
