### ISSUE TITLE
Details about antivirus disable requirement?

### ISSUE THREAD

**Issue by devnewton** [OpenIdentityPlatform/OpenDJ#172]
**Is your feature request related to a problem? Please describe.**

The installation preparation guide ask to "Prevent antivirus and intrusion detection systems from interfering with OpenDJ directory server" without further explanation. This make our chief information security officer very suspicious about OpenDJ :-(

**Describe the solution you'd like**
Add details about the reason to prevent antivirus to scan OpenDJ files.

**Comment by vharseko** [comment]
recommendation only
