### ISSUE TITLE
OpenDJ doesn't start when using Prometheus' jmx_exporter as javaagent paramete

### ISSUE THREAD

**Issue by FlyingHe** [OpenIdentityPlatform/OpenDJ#174]
> **Describe the bug**
> **same with the issues has been closed** [https://github.com/OpenIdentityPlatform/OpenDJ/issues/83#issue-473899348](url)
> I'm trying to convert JMX to Prometheus metrics using the official Prometheus plugin jmx_exporter (https://github.com/prometheus/jmx_exporter) as java agent. The problem is that when I use jmx_export jar as a -javaagent parameter, OpenDJ doesn't start. Application crashes during _script-util.sh execution with the following error:
> 
> ```
>FATAL ERROR in native method: processing of -javaagent failed
>/opt/app/opendj-4.4.10/opendj/lib/_script-util.sh: line 136:  1158 Aborted                 "${OPENDJ_JAVA_BIN}" >${OPENDJ_JAVA_ARGS} org.opends.server.tools.CheckJVMVersion 2> /dev/null
>ERROR:  The detected Java version could not be used with the set of Java
>arguments -server -Xmx8192m -Xms4096m -javaagent:/opt/app/opendj-4.4.10/opendj/jmx_prometheus_javaagent->0.15.0.jar=8080:/opt/app/opendj-4.4.10/opendj/promethues_config.yaml.
>The detected Java binary is: /opt/app/jdk1.8.0_45/bin/java
>You must specify the path to a valid Java 7 or higher version.
>The procedure to follow is to set the environment variable OPENDJ_JAVA_HOME
>to the root of a valid Java 7 installation.
>If you want to have specific Java settings for each command line you must
>edit the properties file specifying the Java binary and/or the Java arguments
>for each command line.  The Java properties file is located in:
>/opt/app/opendj-4.4.10/opendj/config/java.properties.
> ```
> 
> **To Reproduce**
> **my jdk is jdk1.8.0_45 , opendj is 4.4.10 , jmx_exporter is 0.15.0**
> Steps to reproduce the behavior:
> 
> 1. unpack opendj and run basic setup script with
> 
> ```
> opendj/setup
>     --cli --baseDN '{{ opendj_basedn }}'
>     --addBaseEntry
>     --ldapPort {{ opendj_ldap_port }}
>     --adminConnectorPort {{ opendj_admin_port }}
>     --rootUserDN '{{ ldap_admin_user }}'
>     --rootUserPassword '{{ ldap_admin_pass }}'
>     --no-prompt
>     --noPropertiesFile
>     --doNotStart"
> ```
> 
> 1. Enable JMX on port 1689
> 
> ```
> opendj/bin/dsconfig set-connection-handler-prop --hostname localhost --port 4444 --bindDN "cn=Directory Manager" --bindPassword password --handler-name "JMX Connection Handler" --set enabled:true --set listen-port:1689 --trustAll --no-prompt
> 
> opendj/bin/dsconfig -h localhost -p 4444 -D "cn=Directory Manager" -w password -n set-root-dn-prop --add default-root-privilege-name:jmx-read --add default-root-privilege-name:jmx-write --add default-root-privilege-name:jmx-notify --trustAll --no-prompt
> ```
> 
> 1. Download jmx_exporter (https://github.com/prometheus/jmx_exporter) java agent for Prometheus from `https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar`
> 2. Create a config file for jmx_exporter and name it config.yaml
> 
> ```
>---
>startDelaySeconds: 0
>username: cn=Directory Manager
>password: password
>jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:1689/jmxrmi
>ssl: false
>lowercaseOutputName: false
>lowercaseOutputLabelNames: false
>whitelistObjectNames:
>  - "org.opends.server:Name=*,Rdn1=*,Rdn2=*"
>  - "org.opends.server:Name=*,Rdn1=*,Rdn2=*,Rdn3=*"
>rules:
> ```
> 
> 1. Add java agent parameter to java args for start-ds. Replace line `start-ds.java-args=-server` in config/java.properties with `start-ds.java-args=-server -Xmx8192m -Xms4096m -javaagent:/opt/app/opendj-4.4.10/opendj/jmx_prometheus_javaagent-0.15.0.jar=8080:/opt/app/opendj-4.4.10/opendj/promethues_config.yaml`
> 2. Start the server with bin/start-ds. Error from description is shown on the console.
> 
> **Expected behavior**
> OpenDJ would start and I would be able to access Prometheus metrics via http endpoint localhost:8080/metrics
> 
> I think that fixing this problem would be beneficial for a lot of users. To the best of my knowledge, there is currently no other way to export metrics to Prometheus from OpenDJ.

**Comment by vharseko** [comment]
not bug
please check config.yaml
```
/usr/bin/java -server -javaagent:/Users/vharseko/Downloads/jmx_prometheus_javaagent-0.16.1.jar=8080:/tmp/config.yaml org.opends.server.tools.CheckJVMVersion
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NullPointerException
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:185)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```
