### ISSUE TITLE
opendj_service.exe executable can throw error r6002

### ISSUE THREAD

**Issue by adipose** [OpenIdentityPlatform/OpenDJ#183]
When using this utility via PTC software, I could not update the windows service, and I tracked it down this error:

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/c-runtime-error-r6002?view=msvc-160

I recompiled opendj_service.exe with visual studio 2019, and used that exe instead, which solved the problem.  The source did not require any changes.  Maybe a newer build is worth including.

**Comment by vharseko** [comment]
please make PR for https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-server-legacy/lib/opendj_service.exe
