### ISSUE TITLE
alias objectClass cause replication error

### ISSUE THREAD

**Issue by pinocc01** [OpenIdentityPlatform/OpenDJ#194]
I try turn on replication, but always fail, and get error log like this when do replication initialize

`[19/Oct/2021:17:18:30 +0800] category=SYNC severity=ERROR msgID=35 msg=A loop was detected while replaying operation: ModifyOperation(connID=-1, opID=245, dn=uid=ljd326,ou=abc,dc=ge) error Entry uid=ljd326,ou=abc,dc=ge cannot be modified because no such entry exists in the server`

at last, I remove all entrys with alias objectClass, then replication done

Version 4.4.11

**Comment by vharseko** [comment]
cannot reproduce, please provide setup/import script
