### ISSUE TITLE
members of posixGroup not found

### ISSUE THREAD

**Issue by partyzan543** [OpenIdentityPlatform/OpenDJ#197]
Sorry for my bad english.. I need to grant access rights to members of posixGroup (aci). But it doesn't work. If you specify groupofnames, then everything is fine.
for example aci rule

ds-cfg-global-aci: (targetattr="testattr")(version 3.0; acl "test"; allow(write) (groupdn = "ldap:///cn=admins,ou=groups,dc=example,dc=com");)
and this option doesn't work either
ds-cfg-global-aci: (targetattr="testattr")(version 3.0; acl "test"; allow(write) (userdn = "ldap:///memberUid=*,cn=admins,ou=groups,dc=example,dc=com");)

how to create a aci rule for posixGroup?

_Originally posted by @partyzan543 in https://github.com/OpenIdentityPlatform/OpenDJ/issues/169#issuecomment-952733607_

**Comment by chenss-1** [comment]
I find posixGroup isn't  STRUCTURAL, so can't add cn

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.5.5
