### ISSUE TITLE
Bug at Windows Version 4.4.11

### ISSUE THREAD

**Issue by NikyMandl** [OpenIdentityPlatform/OpenDJ#199]
Hello.

Short Info to opdenDJ Version 4.4.11 is not working on Windows Versions.
OpenDJ Server ist starting and startet in windows Services.
issue is, that login with control Panel or into LDAP is not possible.
After analyse this problem, i see with TCP View, that service is never running with ports 389,636,4444.
So service is runnging but using no ports and so communication is not possible.
i searched the Log folders for errors, but can not find one.

Tried to start the service with local Administrator credentials -- also no function.
Set it to start with adminisrator rights -- also no function.
uninstalled all and installed new with Administrator rights and settings -- but no function. 
installed it on Windows Server 2012 R2, Windows Server 2019, Windows 10 20H2. but on every System no function

I think there is global Problem in Windows version 4.4.11
tryed an older 2.7 Version, all is OK. 

Please help, or have anyone infos to get it running????

**Comment by ATLJLawrie** [comment]
I ran into some of the same and found the secret was to not let it install in the default C:\Program Files (x86)\OpenDJ location but instead some path off of C:\.  `msiexec /i DS-4.4.11.msi /l* install.log /q OPENDJ=C:\opendj-4.4.11` by doing that setup.bat actually worked for both GUI and CLI and everything setup properly.
