### ISSUE TITLE
Man page links other than pdf result in Failed to fetch version info for wiki/OpenIdentityPlatform.

### ISSUE THREAD

**Issue by lucastheisen** [OpenIdentityPlatform/OpenDJ#200]
**Describe the bug**
Click on any of the man page links from the [See also section of the Admin guide](https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Administration#see-also) and you will see:

> Failed to fetch version info for wiki/OpenIdentityPlatform.

**To Reproduce**
1. Click on webhelp/html/xhtml links from the See also section

**Expected behavior**
Man pages

**Screenshots**
![image](https://user-images.githubusercontent.com/1952786/143719965-48daed0c-f212-417a-8aac-a9b3c0493556.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version  94.0.2

**Additional context**
pdf's seem to work fine

**Comment by maximthomas** [comment]
Thank you for the issue, just fixed links

**Comment by lucastheisen** [comment]
@maximthomas , the link is no longer _failing_, but also don't think it is actually what you intend:

![image](https://user-images.githubusercontent.com/1952786/143909639-7b3232e8-0db1-4001-ad39-031ab327e068.png)

**Comment by maximthomas** [comment]
Unfortunately, GitHub returns invalid content type for such pages, so it can't be fixed on our side
As a workaround, you can save the page on your machine and open it.

![image](https://user-images.githubusercontent.com/7863782/144477836-7e83b527-eedf-41af-be58-9720b70b1e35.png)
