### ISSUE TITLE
tamil (ta.6) matching rule schema has typo in definition

### ISSUE THREAD

**Issue by maxfieb** [OpenIdentityPlatform/OpenDJ#203]
**Describe the bug**
The matching for tamir (ta.6) has a typo (live schema copied as ldif fragment, from 4.4.11 running instance) :

```
matchingRules: ( 1 3 1.3.6.1.4.1.42.2.27.9.4.134.1.6 NAME ( 'ta.6' 'ta.sub'
  ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'OpenDS Directory Server' 
 )
```

I don't have any entries using this locale, but it causes a parse issue with schema parsing, its visible as above or
when browsing with apache directory studio. This seems to be addressed in OPENDJ-6970 (upstream) by fixing
the typo in  typo in CoreSchemaSupportedLocales [here](https://github.com/OpenIdentityPlatform/OpenDJ/blob/4b64543c12cfc61571f6fcb9af2d4a510283e20b/opendj-core/src/main/java/org/forgerock/opendj/ldap/schema/CoreSchemaSupportedLocales.java#L199)

Fix looks like to replace 

`LOCALE_NAMES_TO_OIDS.put("ta", "1 3  1.3.6.1.4.1.42.2.27.9.4.134.1");`

With

`LOCALE_NAMES_TO_OIDS.put("ta", "1.3.6.1.4.1.42.2.27.9.4.134.1");`

And rebuild.

**To Reproduce**

```
bin/ldapsearch -h localhost -p 2389 -b cn=schema -s base "(&)" matchingRules|grep ta.sub
matchingRules: ( 1 3 1.3.6.1.4.1.42.2.27.9.4.134.1.6 NAME ( 'ta.6' 'ta.sub' ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'OpenDS Directory Server' )
```

**Expected behavior**

OIDs such as "1 3 1.3.6.1.4.1.42.2.27.9.4.134.1.6" are invalid, first number is an OID, which can contain spaces, so will cause issues if a schema parser is following the specs, and not ignoring errors, as spaces are considered part of the syntax in schema definitions.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by akaer** [comment]
Error is also in latest Docker release with Tag 4.4.14
