### ISSUE TITLE
RelaxRules doesnt appear to work for setting pwdChangedTime

### ISSUE THREAD

**Issue by lucastheisen** [OpenIdentityPlatform/OpenDJ#204]
**Describe the bug**
Unable to use the `ldapmodify --control RelaxRules:true` to set the `pwdChangedTime` in order to facilitate integration testing of password policy.  [This blog](https://ludopoitou.com/2019/01/17/forgerock-ds-and-the-ldap-relax-rules-control/) seems to indicate support for the control at some level, and [this jira issue](https://bugster.forgerock.org/jira/browse/OPENDJ-4437) indicates it was _merged_ in fixVersion 6.5 (which i am not sure how forgerock versions relate to opendj versions). I also searched the [latest admin guide](https://backstage.forgerock.com/search?q=relaxrules&t=doc&filter=productId:eq:ds&filter=version:eq:7.1) which is very slim on related content, the [google group](https://groups.google.com/d/forum/open-identity-platform-opendj) linked to as _OpenDJ Community Archive_ seems to have been removed, and posted a question on [Gitter](https://gitter.im/OpenIdentityPlatform/OpenDJ?at=61b7cb2b8853d3164047e432) which doesn't appear to have a lot of activity.

**To Reproduce**
1. Create a user
2. Attempt to change password changed time with
   ```console
   ldapmodify \
     --bindDN "cn=Directory Manager" \
     --bindPassword set4now \
     --hostname localhost \
     --port 3389 \
     --control RelaxRules:true <<EOF
   dn: uid=kermitthefrog,ou=people,dc=example,dc=com
   control: 1.3.6.1.4.1.4203.666.5.12
   changetype: modify
   replace: pwdChangedTime
   pwdChangedTime: 20211203224637.000Z
   EOF
   ```
3. See:
   ```console
   Processing MODIFY request for
   uid=kermitthefrog,ou=people,dc=example,dc=com
   The LDAP modify request failed: 12 (Unavailable Critical Extension)
   Additional Information:  Entry
   uid=kermitthefrog,ou=people,dc=example,dc=com cannot be modified
   because the request contained a critical control with OID RelaxRules that is
   not supported by the Directory Server for this type of operation
   ```

**Expected behavior**
`pwdChangedTime` gets explicitly set value

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.03
 - Browser: n/a
 - Version: n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Currently using OpenDJ 4.4.11

**Comment by vharseko** [comment]
fixed [4.7.0](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.7.0)
