### ISSUE TITLE
What is the configuration file path, where all the conf properties stores ?

### ISSUE THREAD

**Issue by khasim4A2** [OpenIdentityPlatform/OpenDJ#239]
To make opendj service to systemd service, i'm looking for the configuration file path in which all the input properties given to setup command. Can someone help me to find it. If the opendj service already available as a systemd service please let me know. Thank you.

**Comment by vharseko** [comment]
try **create-rc-script** in  https://github.com/OpenIdentityPlatform/OpenDJ/wiki/docbkx/pdf/OpenDJ-Man-Pages.pdf
