### ISSUE TITLE
Review of Docs migrate Install guide #20 

### ISSUE THREAD

**Issue by kurnysh** [OpenIdentityPlatform/OpenDJ#24]
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide

**Comment by vharseko** [comment]
my changes: https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide/_compare/7c565094098d57f66b2310f4d559a9c738b345e8...8ca13e4adb2f3b054a46e572a22bea2c86e1fd32

@maximthomas  please check and close

**Comment by maximthomas** [comment]
Fixed image, https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide/993ef2b74645f1a3b660fb979821dd8002084e7f
