### ISSUE TITLE
dsreplication initialization failed(30 million entries)

### ISSUE THREAD

**Issue by gcd4** [OpenIdentityPlatform/OpenDJ#241]
Hi,
We are using opendj-4.4.11，jdk11.
Source server 30 million entries， using  dsreplication  initialize   destination server ， throw exception  "Entry uid=abcde,ou=InterUsers,o=Inter,dc=jindian,dc=com cannot be added because its parent entry u=InterUsers,o=Inter,dc=jindian,dc=com does not exist in the server".  
Thank you.

**Comment by yavis73** [comment]
Hi,
Get an ldif backup of your data from the source server.
And then ㅊheck that the order of the entries in the ldif is correct.
The cause is unknown, but sometimes unexpected results occur.
Find the cause one by one.

Good luck..

**Comment by vharseko** [comment]
invalid ldif order
