### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by diegogmanzanares** [OpenIdentityPlatform/OpenDJ#250]
I have configured 2 backend:

1. name userRoot  - dn --> o=company
2. name userRoot2 - dn --> dc=eus,o=company

![image](https://user-images.githubusercontent.com/9338317/185595316-0b2e634c-fbb3-4291-b0c8-66ae9bffafcc.png)

![image](https://user-images.githubusercontent.com/9338317/185595501-a5948a7d-f6ad-4b05-83dd-8326154fbc48.png)

If I do a paged search with base dn o=company all user, the search enter in a loop o no show all result. 
If the paged search is with dn dc=es,o=company or dc=eus,o=company, the search works ok.

The problem is with the page cookie.

Thanks

**Comment by vharseko** [comment]
cannot reproduce in [core](https://github.com/vharseko/OpenDJ/commit/03a2195286f202c50737674e105fb583f72e24ae) and in **control-panel** (tested on [4.6.5](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.6.5))

<img width="549" alt="Снимок экрана 2024-08-06 в 11 26 40" src="https://github.com/user-attachments/assets/a47eb625-044d-4925-9452-c6102156a030">
<img width="691" alt="Снимок экрана 2024-08-06 в 11 26 12" src="https://github.com/user-attachments/assets/0035c944-7711-42a8-b708-1c860e569534">
<img width="814" alt="Снимок экрана 2024-08-06 в 11 25 56" src="https://github.com/user-attachments/assets/64094ef6-4d73-4e86-87e0-081cf83f6b41">
<img width="839" alt="Снимок экрана 2024-08-06 в 11 25 45" src="https://github.com/user-attachments/assets/9b7e0a3a-9907-42f5-9942-1e65d9194566">
