### ISSUE TITLE
HTTP Authentication with custom unique id + password in --user  

### ISSUE THREAD

**Issue by stardev24** [OpenIdentityPlatform/OpenDJ#251]
We are using earlier Forgerock Opendj v3.0 and in that we have additional custom unique attribute apart from uid.To do basic HTTP authentication we are using --user customuid:password and it is working fine.

But when I try to do same v4.0 I am getting invalid credentials error while calling /api/users/${uid} api.

is this version 4+ supporting custom uid + password for http rest api authentication or not?
Please help me to understand

**Working in version 3.0**
`
$ curl \
 --user abc-123-def:password \
 https://opendj.example.com:8443/api/users/abc-123-def
`
**Invalid credentials error in v4**
`
$ curl \
 --user abc-123-def:password \
 https://opendj.example.com:8443/api/users/abc-123-def
`
Here abc-123-def is custom uid we created along with actual uid attribute

**Comment by vharseko** [comment]
cannot reproduce

```shell
$bin/ldapmodify --port 1389 --bindDN "cn=Directory Manager" --bindPassword password
dn: uid=abc-123-def,ou=people,dc=example,dc=com
objectClass: top
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
cn: abc-123-def
uid: abc-123-def
sn: abc-123-def
userPassword: password

Processing ADD request for uid=abc-123-def,ou=people,dc=example,dc=com
ADD operation successful for DN uid=abc-123-def,ou=people,dc=example,dc=com
^C

$ curl -u "abc-123-def:password"  http://localhost:8080/api/users/abc-123-def?_prettyPrint=true
{
  "_id" : "abc-123-def",
  "_rev" : "0000000039ec6a9d",
  "_schema" : "frapi:opendj:rest2ldap:user:1.0",
  "_meta" : {
    "created" : "2024-07-09T14:37:29Z"
  },
  "displayName" : [ "abc-123-def" ],
  "name" : {
    "familyName" : "abc-123-def"
  },
  "contactInformation" : { }

```
