### ISSUE TITLE
Java compatibility

### ISSUE THREAD

**Issue by flow555** [OpenIdentityPlatform/OpenDJ#252]
**Is your feature request related to a problem? Please describe.**
It is very unclear which version of java is compatible or tested against.

**Describe the solution you'd like**
More information on the page https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Release-Notes#java-environment

**Describe alternatives you've considered**
I checked other Issues for compatibility

**Additional context**
It seems the Java Environment section is quite outdated, as it is still referencing Java JRE 7 and 8. I found some issues (e.g. #28 ) asking if OpenDJ is compatible with Java 11, which was confirmed.
To me it's not very clear if it is recommended to use the latest update of Java 7/8 or if its recommended to use the newest Java version (e.g. Java 18). It would be helpful to know which version to use to have the least amount of trouble.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Release-Notes/_compare/74ed6fc22c9743341dd39ea507462d6b15121d45...e668a7877f95eac3e5118d0ae61c2edec21b289a
