### ISSUE TITLE
objectClass: groupOfNames

### ISSUE THREAD

**Issue by b0x68** [OpenIdentityPlatform/OpenDJ#269]
Hi.

I've migrated from Sun DSEE7 to OpenDJ. In the DSEE7 system, we did not use `objectClass: groupOfNames`, however, in OpenDJ I see numerous group entries with this objectClass and the 'member' attribute present. Can anyone tell me why this gets applied to only _some_ group entries? It is conflicting with another stuctural `objectClass: posixGroup`. I am not seeing the difference between the groups that have the `objectClass: groupOfNames` versus the groups that do not. 

> [21/Dec/2022:15:19:50 -0500] category=CORE severity=ERROR msgID=198 msg=Entry cn=cosXXX,ou=Group,dc=cs,dc=university,dc=edu violates the Directory Server schema configuration because it includes multiple conflicting structural objectclasses posixGroup and groupOfNames. Only a single structural objectclass is allowed in an entry.

For example:
`ldapsearch -x -D cn=manager -W -b "ou=Group,dc=cs,dc=university,dc=edu" -s sub`

Returns all OUs of "ou=Group,dc=cs,dc=university,dc=edu". Some of these groups have more than one member, but not all those entries have the objectClass: groupOfNames.

dn: cn=cosXXX,ou=Group,dc=cs,dc=university,dc=edu
objectClass: top
objectClass: posixGroup
gidNumber: 11111
memberUid: member1
memberUid: member2
memberUid: member3
memberUid: member4
cn: cosXXX

dn: cn=coordinator,ou=Group,dc=cs,dc=university,dc=edu
objectClass: top
objectClass: posixGroup
objectClass: groupOfNames
gidNumber: 11112
cn: coordinator
memberUid: member11
memberUid: member12
memberUid: member13
member: cn=member11,ou=People,dc=cs,dc=university,dc=edu
member: cn=member12,ou=People,dc=cs,dc=university,dc=edu
member: cn=member13,ou=People,dc=cs,dc=university,dc=edu

Thank you!

**Comment by yavis73** [comment]
Hello.
The error message seems to be a problem with environment settings.

Change the "single-structural-objectclass-behavior" setting from the default "reject" to "accept" in the Global Configuration and try again.

For details, use "help" to check.

good luck.

**Comment by b0x68** [comment]
Thanks for the reply
