### ISSUE TITLE
font awesome url Error

### ISSUE THREAD

**Issue by nejeoui** [OpenIdentityPlatform/OpenDJ#27]
maven install try to download font awesome from : 
 downloading artifact from URL: https://github.com/FortAwesome/Font-Awesome/archive/v4.5.0.zip

it should be  https://github.com/FontAwesome instead of  https://github.com/FortAwesome

**Comment by maximthomas** [comment]
@nejeoui i've tried to launch maven install on OpenDJ project, and have not seen any record about Font-Awesome in installation log. Could you provide more details about this error or attach maven log?

**Comment by vharseko** [comment]
https://github.com/FortAwesome/Font-Awesome/network/members <https://github.com/FortAwesome/Font-Awesome> is trusted source
