### ISSUE TITLE
bin/restore argument --listBackups ERROR

### ISSUE THREAD

**Issue by b0x68** [OpenIdentityPlatform/OpenDJ#271]
**Describe the bug**
`/opt/opendj/bin/restore --backupDirectory /opt/opendj/bak --listBackups` or `-l`

> ERROR:  argument listBackups is incompatible with use of this tool to interact
> with the directory as a client

**To Reproduce**
```
bin/stop-ds

bin/status
--- Server Status ---
Server Run Status:  Stopped
...
/opt/opendj/bin/restore --backupDirectory /path/to/backup --listBackups
```
>  ERROR:  argument listBackups is incompatible with use of this tool to interact
> with the directory as a client

**Expected behavior**
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Administration-Backups#92-restoring-directory-data-from-backup

**Specs:**
 - OS: RHEL 8.5
 - OpenDJ Version: 4.4.11
 - Java Version: 11.0.12

**Additional context**
Planning an upgrade from 4.4.11 and going through the process of backups/restore etc and found this issue.

Thanks,
Brian

**Comment by yavis73** [comment]
Hello. 

This is an embarrassing error message.

It works different from the documentation...

It seems to happen the same on all versions.

In the source that operates the command, when using "listBackups", it is forced to use the "offline" option unconditionally, and if not, the corresponding message is output. ( https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-server-legacy/src/main/java/org/opends/server/tools/RestoreDB.java ( 222 ~ 225 ) )

I don't know if this is a source issue or a documentation issue.

I don't know the purpose of the logic on this source.

There are workaround to this problem.
1. Use the listBackups option must be used  together with the offline option
2. Use it after fixing the source of the part......

Good luck...

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.5.5
