### ISSUE TITLE
Can provide api for services like ldapjs library, custom implementation like crud interface to complete persistence?

### ISSUE THREAD

**Issue by weijie0** [OpenIdentityPlatform/OpenDJ#272]
**Is your feature request related to a problem? Please describe.**
I need to authenticate with my existing data already completed, this is usually an interface or database, however it is difficult

**Describe the solution you'd like**
I'd like to use the ldapjs library like a server-side api to complete the crud implementation.

**Describe alternatives you've considered**

**Additional context**

**Comment by vharseko** [comment]
please check https://github.com/OpenIdentityPlatform/OpenDJ/wiki/old/OpenDJ-3.5-Server-Dev-Guide.pdf
