### ISSUE TITLE
Connection on admin port times out

### ISSUE THREAD

**Issue by ettr02** [OpenIdentityPlatform/OpenDJ#273]
**Describe the bug**
When the opendj is under high load the connection with admin user times out and a connection is until restart impossible.
Example call:  **bin/ldapsearch -X -Z -h localhost -p 4444 -D "cn=tecAdmin,cn=Root DNs,cn=config" -w ****  -b dc=data,dc=test "(mail=Test*)" dn**
Other admin user also fail!
**Is there a way to reactivate the admin port?**

**To Reproduce**
1. set opendj under pressure
2. call ldapsearch after a while an more then once, there is no pattern I could find.
4. See error:
 The LDAP search request failed: 91 (Connect Error)
Additional Information:  The connection attempt to server localhost/127.0.0.1:4444 has failed because the connection timeout period of 30000 ms was exceeded

**Expected behavior**
ldapsearch result

**Desktop (please complete the following information):**
 - OS: Linux Suse SLES 12

**Additional context**
opendj 4.5.2

**Comment by aadrii** [comment]
Got the same "behaviour", but was due to errors during init, cf https://github.com/OpenIdentityPlatform/OpenDJ/issues/274#issuecomment-1541706522

**Comment by vharseko** [comment]
try use client port 389/636
admin connection -p 4444 allow single user
