### ISSUE TITLE
Editing 'gecos' schema syntax causes 'posixAccount' to be removed and creates a duplicate OID

### ISSUE THREAD

**Issue by b0x68** [OpenIdentityPlatform/OpenDJ#277]
OpenDJ 4.4.11
RHEL 7.9

Currently, our production LDAP servers are on OpenDJ 4.4.11. We did not have a pre-prod environment so I decided to make one for upgrade testing. While setting up the server to match production, I encounter schema issues.

I need to update the 'gecos' attributeType that comes with an OpenDJ install. We have users who need the syntax 1.3.6.1.4.1.1466.115.121.1.15 for accents, etc. I apply the following:

```
/opt/opendj/bin/ldapmodify --port 389 --bindDn cn=manager --bindPassword $CNMAN /opt/opendj/ldif/mod_gecos.ldif
```
which contains:

```
dn: cn=schema
changetype: modify
delete: attributeTypes
attributeTypes: ( 1.3.6.1.1.1.1.2 NAME 'gecos' DESC 'The GECOS field; the common name' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 SINGLE-VALUE X-ORIGIN '04-rfc2307bis.ldif' )
-
add: attributeTypes
attributeTypes: ( 1.3.6.1.1.1.1.2 NAME 'gecos' DESC 'The GECOS field; the common name' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE X-ORIGIN 'draft-howard-rfc2307bis' X-SCHEMA-FILE '99-user.ldif' )
```
This completes successfully, but then after several minutes OR a service restart, `/opt/opendj/bin/stop-ds --restart` I get the following:

> category=CONFIG severity=WARNING msgID=761 msg=The config schema file '04-rfc2307bis.ldif' generated warning when trying to update schema with its content: [Unable to register attribute type name with the server schema because its OID 2.5.4.41 conflicts with the OID of an existing attribute type name, Validation of object class definition ( 1.3.6.1.1.1.2.0 NAME 'posixAccount' DESC 'Abstraction of an account with POSIX attributes' SUP top AUXILIARY MUST ( cn $ uid $ uidNumber $ gidNumber $ homeDirectory ) MAY ( authPassword $ userPassword $ loginShell $ gecos $ description ) X-ORIGIN 'draft-howard-rfc2307bis' X-SCHEMA-FILE '04-rfc2307bis.ldif' ) failed and will be removed from the schema: The object class "posixAccount" specifies the optional attribute type "gecos" which is not defined in the schema]

Prior to the 'gecos' update, service restarts never show the above warnings and error messages. Can anyone reproduce this?

**Comment by b0x68** [comment]
UPDATE:

I resolved the following error: 

> Validation of object class definition ( 1.3.6.1.1.1.2.0 NAME 'posixAccount' DESC 'Abstraction of an account with POSIX attributes' SUP top AUXILIARY MUST ( cn $ uid $ uidNumber $ gidNumber $ homeDirectory ) MAY ( authPassword $ userPassword $ loginShell $ gecos $ description ) X-ORIGIN 'draft-howard-rfc2307bis' X-SCHEMA-FILE '04-rfc2307bis.ldif' ) failed and will be removed from the schema: The object class "posixAccount" specifies the optional attribute type "gecos" which is not defined in the schema]

By removing `X-SCHEMA-FILE '99-user.ldif` with `X-SCHEMA-FILE 04-rfc2307bis.ldif'`, however, I still get the following error after opendj service restarts and/or manually removing the duplicate line when the service is stopped:

> 
[13/Mar/2023:13:17:49 -0400] category=CONFIG severity=WARNING msgID=761 msg=The config schema file '04-rfc2307bis.ldif' generated warning when trying to update schema with its content: [Unable to register attribute type name with the server schema because its OID 2.5.4.41 conflicts with the OID of an existing attribute type name]

**Comment by yavis73** [comment]
Hi.
 Before removing the attribute, you must first delete the objectclass that uses the attribute. 

Then add the modified attribute and the deleted objectclass. 
( objectclass delete --> attribute delete --> attibute add --> objectclass add )

When making changes or additions to the '04-rfc2307bis.ldif' file, 

 attributeTypes '(2.5.4.41 NAME 'name' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'RFC 4519' X-SCHEMA-FILE '00-core.ldif')' 

is automatically inserted. 

You need to manually delete it.

Which appears to be a bug.

**Comment by b0x68** [comment]
Thanks for the note. To confirm, I've been able to reproduce the bug in 4.5.4. I've found that any ldapmodify operation I try, even prior to any data being imported, causes the duplicate OID. Manually removing it seems to be the workaround. For example:

```
dn: cn=schema
changetype: modify
delete: attributeTypes
attributeTypes: ( 1.3.6.1.1.1.1.2 NAME 'gecos' DESC 'The GECOS field; the common name' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.26 SINGLE-VALUE X-ORIGIN '04-rfc2307bis.ldif' )
-
delete: objectClasses
objectClasses: ( 1.3.6.1.1.1.2.0 NAME 'posixAccount' DESC 'Abstraction of an account with POSIX attributes' SUP top AUXILIARY MUST ( cn $ uid $ uidNumber $ gidNumber $ homeDirectory ) MAY ( authPassword $ userPassword $ loginShell $ gecos $ description ) X-ORIGIN 'draft-howard-rfc2307bis' X-SCHEMA-FILE '04-rfc2307bis.ldif' )
-
add: attributeTypes
attributeTypes: ( 1.3.6.1.1.1.1.2 NAME 'gecos' DESC 'The GECOS field; the common name' EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE X-ORIGIN '04-rfc2307bis.ldif' X-SCHEMA-FILE '04-rfc2307bis.ldif' )
-
add: objectClasses
objectClasses: ( 1.3.6.1.1.1.2.0 NAME 'posixAccount' DESC 'Abstraction of an account with POSIX attributes' SUP top AUXILIARY MUST ( cn $ uid $ uidNumber $ gidNumber $ homeDirectory ) MAY ( authPassword $ userPassword $ loginShell $ gecos $ description ) X-ORIGIN 'draft-howard-rfc2307bis' X-SCHEMA-FILE '04-rfc2307bis.ldif' )
```

And..

```
dn: cn=schema
changetype: modify
delete: objectClasses
objectClasses: ( 1.3.6.1.1.1.2.2 NAME 'posixGroup' SUP top AUXILIARY DESC 'Abstraction of a group of accounts' MUST ( cn $ gidNumber ) MAY ( authPassword $ userPassword $ memberUid $ description ) X-ORIGIN 'draft-howard-rfc2307bis' )
-
add: objectClasses
objectClasses: ( 1.3.6.1.1.1.2.2 NAME 'posixGroup' SUP top STRUCTURAL DESC 'Abstraction of a group of accounts' MUST ( cn $ gidNumber ) MAY ( authPassword $ userPassword $ memberUid $ description ) X-ORIGIN 'draft-howard-rfc2307bis' )
```
