### ISSUE TITLE
PBKDF2-HMAC-SHA256 and PBKDF-HMAC-SHA512 password storage not configured by default

### ISSUE THREAD

**Issue by maxfieb** [OpenIdentityPlatform/OpenDJ#281]
**Describe the bug**

The password storage schemes PBKDF2-HMAC-SHA256 and PBKDF-HMAC-SHA512 added in opendj-4.4.15 seems to not have the schema required to operate.

PR-228 introduced "Implement PBKDF2-HMAC-SHA256 and PBKDF-HMAC-SHA512 password encoding schemes by @lscorcia in https://github.com/OpenIdentityPlatform/OpenDJ/pull/228"

Root cause is possibly ds-cfg-pbkdf2-hmac-sha256-password-storage-scheme and ds-cfg-pbkdf2-hmac-sha512-password-storage-scheme do not exist in the server schema, and these password storage schemes are not initializing on server startup ? 

I can confirm that no object schemas starting with ds-cfg-pbkdf2 exist, other than ds-cfg-pbkdf2-password-storage-scheme which is the SHA1 version of PBKDF2 which is relatively weak, and has some hash collision problems due to using SHA1.

**To Reproduce**

Using release 4.5.4

>>>> Select the type of Password Storage Scheme that you want to create:

    1)   AES Password Storage Scheme      11)  PBKDF2 Hmac SHA512 Password
                                               Storage Scheme
    2)   Base64 Password Storage Scheme   12)  PKCS5S2 Password Storage Scheme
    3)   Bcrypt Password Storage Scheme   13)  RC4 Password Storage Scheme
    4)   Blowfish Password Storage        14)  Salted MD5 Password Storage
         Scheme                                Scheme
    5)   Clear Password Storage Scheme    15)  Salted SHA1 Password Storage
                                               Scheme
    6)   Crypt Password Storage Scheme    16)  Salted SHA256 Password Storage
                                               Scheme
    7)   Custom Password Storage Scheme   17)  Salted SHA384 Password Storage
                                               Scheme
    8)   MD5 Password Storage Scheme      18)  Salted SHA512 Password Storage
                                               Scheme
    9)   PBKDF2 Password Storage Scheme   19)  SHA1 Password Storage Scheme
    10)  PBKDF2 Hmac SHA256 Password      20)  Triple DES Password Storage
         Storage Scheme                        Scheme

    ?)   help
    c)   cancel
    q)   quit

Enter choice [c]: 10

>>>> Enter a name for the PBKDF2 Hmac SHA256 Password Storage Scheme that you
want to create: PBKDF2-HMAC-SHA256

>>>> Configuring the "enabled" property

    Indicates whether the Password Storage Scheme is enabled for use.

Select a value for the "enabled" property:

    1)  true
    2)  false

    ?)  help
    c)  cancel
    q)  quit

Enter choice [c]: 1

>>>> Configure the properties of the PBKDF2-HMAC-SHA256

        Property           Value(s)
        -----------------------------------------------------------------------
    1)  enabled            true
    2)  java-class         org.opends.server.extensions.PBKDF2HmacSHA256PasswordStorageScheme
    3)  pbkdf2-iterations  10000

    ?)  help
    f)  finish - create the new PBKDF2-HMAC-SHA256
    c)  cancel
    q)  quit

Enter choice [f]: 

The PBKDF2 Hmac SHA256 Password Storage Scheme could not be created due to a
communications problem: Object Class Violation: Entry
cn=PBKDF2-HMAC-SHA256,cn=Password Storage Schemes,cn=config violates the
Directory Server schema configuration because it contains an unknown
objectclass ds-cfg-pbkdf2-hmac-sha256-password-storage-scheme

Press RETURN to continue

**Expected behavior**
Server should start and PBKDF2-HMAC-SHA256 and PBKDF-HMAC-SHA512 be avalable to encode passwords.

They are not available by default, possibly these objectclasses need to be added to the server schema ?

ds-cfg-pbkdf2-hmac-sha256-password-storage-scheme
ds-cfg-pbkdf2-hmac-sha512-password-storage-scheme

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Rocky 8 (centos8/rhel8)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.5.5
