### ISSUE TITLE
OpenDJ not dereferencing aliases

### ISSUE THREAD

**Issue by kranskydog** [OpenIdentityPlatform/OpenDJ#287]
**Describe the bug**
if I create an alias to another object, and do an ldapsearch on the alias, I do not get back anything about the aliased object. I only get back the alias definition

**To Reproduce**

create an object
create an alias for that object
use 'ldapsearch -a always' to search for the alias

**Expected behavior**
I should get back the details of the aliased object 

**Screenshots**
[root@ldap11 ~]# ldapsearch -LL -a always -h $(hostname) -p 389 -x -b "cn=OracleContext,dc=example,dc=com" -s sub "(cn=foo)" 
version: 1

dn: cn=foo,cn=OracleContext,dc=example,dc=com
objectClass: top
objectClass: orclNetService
orclNetDescString: (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = orcl.exam
 ple.com)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = f
 oo)))
cn: foo

[root@ldap11 ~]# ldapsearch -LL -a always -h $(hostname) -p 389 -x -b "cn=OracleContext,dc=example,dc=com" -s sub "(cn=bar)" 
version: 1

dn: cn=bar,cn=OracleContext,dc=example,dc=com
objectClass: alias
objectClass: top
objectClass: orclNetServiceAlias
cn: bar
aliasedObjectName: cn=foo,cn=OracleContext,dc=example,dc=com

I expect to get back the orclNetDescString of cn=foo

**Desktop (please complete the following information):**
 - OS: Linux ldap11.example.com 5.4.17-2136.320.7.1.el8uek.x86_64 #2 SMP Sat Jun 10 15:43:58 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
 
**Additional context**
OpenDJ 4.5.4

Using OpenDj to do Oracle TNS name resolution via LDAP.
See, for comparison, https://ronnyegner.wordpress.com/2009/09/25/storing-oracle-database-connection-strings-in-openldap-instead-of-oid/
->'Add an alias'

**Comment by kranskydog** [comment]
RFC 4512, 2.6 Alias Entries
https://www.rfc-editor.org/rfc/rfc4512#page-16

**Comment by vharseko** [comment]
fixed [4.7.0](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.7.0)
