### ISSUE TITLE
issue with OpenDj build with JDK 11.0.1

### ISSUE THREAD

**Issue by rarathore** [OpenIdentityPlatform/OpenDJ#29]
Hi Team,

I tried to build the OpenDj source code with JDK 11.0.1 and Maven Version 3.5.3, I got build failure with 
"[INFO] ForgeRock Guice Library 2.0.0 ...................... FAILURE [  0.463 s]" with below exception 

"[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:checkstyle (check-src-and-tests) on project forgerock-guice: Execution check-src-and-tests of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.16 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.7.0 at specified path /opt/jdk/../lib/tools.jar"

I am trying Out of the box source code of OpenDJ.

I trying to build it on CentOs 7 machine. Please let me know how should I proceed from here.

**Comment by vharseko** [comment]
build with JDK 11 not tested
please build from source with JDK 1.8 and use binary with JDK 11 (tested)


----------------------------------------------------------------------------------
ICQ: 11727046 Skype: vharseko Mobile: +7-917-595-51-55

**Comment by rarathore** [comment]
Hi vharseko,

do we have any plan to build with JDK 11?

**Comment by vharseko** [comment]
yes

**Comment by rarathore** [comment]
so, can you pls share the timeline if possible?

**Comment by vharseko** [comment]
fixed https://travis-ci.org/OpenIdentityPlatform/OpenDJ/builds/465969841
