### ISSUE TITLE
Legacy issues

### ISSUE THREAD

**Issue by FireBurn** [OpenIdentityPlatform/OpenDJ#298]
Hi

I was trying to get OpenDJ/AM 11.0.3 working better with TLS 1.2 & TLS 1.3 and the reduced ciphers in newer Javas

I found that "RSA/ECB/OAEPWITHSHA1ANDMGF1PADDING" is no longer a valid transform cipher

Used the code examples at:
https://stackoverflow.com/questions/9333504/how-can-i-list-the-available-cipher-algorithms 
https://stackoverflow.com/questions/61456475/get-cipher-mode-and-padding-scheme-from-existing-cipher

I don't really understand what's happening in OpenDJ at that level but I changed it to this in the old version:

https://github.com/FireBurn/opendj-community-edition/commit/908b9913414694b1f994d1f902a61851c0841e1a
https://github.com/FireBurn/openam-community-edition/commit/a619d184f2af1aa408b638d7103291123fb3e984

What finally got things working was changing these:

https://github.com/FireBurn/opendj-community-edition/commit/cae605a13d0e43b31cd64f583aca1e1fb048fe89
https://github.com/FireBurn/opendj-community-edition/commit/4eb7801cb068cc4f1844d021e6e86bd68ccd36dc

The RMI one is still set as TLSv1 https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-server-legacy/src/main/java/org/opends/server/protocols/jmx/RmiConnector.java#L288

That might be worth changing

**Comment by vharseko** [comment]
```
SSLContext.getInstance("TLS")
```
?

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/How-To#allow-only-tlsv12-ssl-protocol

**Comment by FireBurn** [comment]
The issue I had came from running OpenDJ embedded in OpenAM

And I don't think you've answered about the transform cipher which OpenDJ uses on creation - which doesn't appear to be valid any more

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/commit/bde0a9a574452fd90abc3a12c90deb8b3d37d6fa
