### ISSUE TITLE
[docker] Upgrade openjdk version for the alpine images

### ISSUE THREAD

**Issue by sco-atolcd** [OpenIdentityPlatform/OpenDJ#328]
Hi,

The openjdk version for the alpine images is still openjdk 8, is there any particular reason it's not jdk 19 like the standard image ?

Thanks.

**Comment by maximthomas** [comment]
Hi, this is the only image that supports platforms: linux/amd64,linux/arm64/8, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6, linux/ppc64le. The latter Docker apline jre images don't support them all.
