### ISSUE TITLE
4.3.2 docker image broken

### ISSUE THREAD

**Issue by nightah** [OpenIdentityPlatform/OpenDJ#35]
**Describe the bug**
The `run.sh` used in the container file is not executable therefore the newest Docker Container `v4.3.2` will not work due to a container is never spawning correctly.

**To Reproduce**
1. Update Docker container from v4.3.1 to v4.3.2 or attempt to run new container based on v4.3.2
2. Container will be unable to run due to the `run.sh` file
3. See error `Cannot start service ldap: OCI runtime create failed: container_linux.go:337: starting container process caused "exec: \"/opt/opendj/run.sh\": permission denied": unknown`

**Expected behavior**
Container should start up as version v4.3.2.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
It appears that the `run.sh` file which is unzipped into the container does not have the executable bit +x.

I have managed to work around this by mounting in a run.sh that is executable but I suggest fixing the file in the git repo to ensure this does not happen again:
`git update-index --chmod=+x OpenDJ\opendj-packages\opendj-docker\run.sh`

Also there are obviously a number of great changes in 4.3.2, however, unless I'm unaware these are not documented anywhere outside of going through the commit log to see what has changed.
The fact that the data directory has moved and a number of other elements like changing the default user will impact peoples existing installs.

Am I missing some detail for these changes? Are these published somewhere?

Thanks for your great work team :).

**Comment by nightah** [comment]
Also FYI.

Looks like this is also an issue for `replication.sh` and `setup.sh`.
Seems that `setup.sh` still runs successfully despite not being executable but `replication.sh` fails.

**Comment by maximthomas** [comment]
@nightah, hello, we just released new OpenDJ version, please, check it out:  [OpenDJ 4.3.3](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.3.3)

**Comment by nightah** [comment]
Thanks for the update @maximthomas I can confirm now that the issues mentioned above appear to be resolved.

https://github.com/OpenIdentityPlatform/OpenDJ/blob/d0f32ac011f3f00b15c9b6eb0bf654bac90ea732/opendj-packages/opendj-docker/Dockerfile#L42-L44
While the above snippet does work, it's not something that is necessary just FYI in future :), you can change the executable bit on the file within the repository per my initial post.

I have also tried playing around with the replication options and to be honest I don't completely understand what the pros and cons of each one appears to be.

I have replication setup between two servers that I manually setup and initialise once but I can't seem to find the exact options to do so within your replication so I would love to know the difference between the replication offerings you included.

Below are the respective commands I run, from what I understand this type of replication is a MASTER/MASTER scenario so any update to either host will be replicated in both directions.

```
./dsreplication enable --adminUID admin \
--adminPassword password \
--baseDN dc=example \
--host1 host1.example \
--port1 4444 \
--bindDN1 "cn=Directory Manager" \
--bindPassword1 password \
--replicationPort1 8989 \
--host2 host2.example \
--port2 4444 \
--bindDN2 "cn=Directory Manager" \
--bindPassword2 password \
--replicationPort2 8989 \
--trustAll \
--no-prompt
```

```
./dsreplication initialize-all --adminUID admin \
--adminPassword password \
--baseDN dc=example \
--hostname host1.example \
--port 4444 \
--trustAll \
--no-prompt
```
