### ISSUE TITLE
Option to specify Cassandra keyspace

### ISSUE THREAD

**Issue by Cenness** [OpenIdentityPlatform/OpenDJ#368]
**Is your feature request related to a problem? Please describe.**
I want to use the same Cassandra cluster for multiple OpenDJ installations, but it uses hardcoded value for keyspace by default.

**Describe the solution you'd like**
Env var or cli flag for setting db-directory on server setup/start

**Describe alternatives you've considered**
Technically one can use dsconfig, but it requires additional actions and is incompatible with simultaneous installation to different namespaces:

1. install OpenDJ
2. run `dsconfig set-backend-prop`
3. stop OpenDJ
4. create new keyspace
5. create snapshot of old keyspace
6. restore data to new keyspace from snapshot
7. delete old keyspace
8. start OpenDJ

dsconfig command for completeness:
```
/opt/opendj/bin/dsconfig -p 4444 -n --trustAll \
                         -D "${ROOT_USER_DN}" \
                         -w ${ROOT_PASSWORD} \
                         set-backend-prop \
                         --backend-name userRoot \
                         --set db-directory:${POD_NAMESPACE}_opendj
```

**Additional context**
I use OpenDJ in k8s clusters.

**Comment by Cenness** [comment]
I'm using similar solution, but with env var. That will work, but backend property will stay as `ldap_opendj`. It's probably only a cosmetic issue, as all actual operations will use value from `getKeyspaceName` anyway.

**Comment by vharseko** [comment]
```bash
#setup without backend
./setup -h localhost -p 1389 --ldapsPort 1636 --adminConnectorPort 4444 --enableStartTLS --generateSelfSignedCertificate --rootUserDN "${ROOT_USER_DN}" --rootUserPassword ${ROOT_PASSWORD} --cli --acceptLicense --no-prompt

#create backend with keyspace: ldap_example_com
bin/dsconfig create-backend \
   --hostname localhost --port 4444 --bindDN "${ROOT_USER_DN}r" --bindPassword ${ROOT_PASSWORD} \
   --backend-name=userRoot \
   --type cas --set db-directory:${POD_NAMESPACE}_${POD_NAME} \
   --set base-dn:dc=example,dc=com \
   --set enabled:true \
   --no-prompt --trustAll
```
