### ISSUE TITLE
control portion of the SearchResultEntry is missing in the LDAP Response

### ISSUE THREAD

**Issue by AdhavanM** [OpenIdentityPlatform/OpenDJ#38]
**Describe the bug**
The control portion of the SearchResultEntry is missing in the LDAP Response .This issue is due to newSearchResultEntry method in the Responses.class takes a Entry class which don't have the control attribute.

opendj-core/src/main/java/org/forgerock/opendj/ldap/responses/Responses.java

**To Reproduce**
1. Register for the callback from the Application client for any changes in the LDAP.
2. Try some updates on the LDAP like Add Entry.
3. In the LDAPResponse received as part of callback , the control attribute is missing which is required to identify the changeType.

**Expected behavior**
searchEntryReturned Bad response; searchEntry.getControls(); searchEntry=SearchResultEntry(dn='UniqueId=trfdecghtyfder,cn=Test,cn=1.0,cn=REST,cn=Test,cn=1.0.0,cn=abc,cn=com,cn=def,dc=new,dc=pa,dc=sw,dc=test,dc=se', messageID=3, attributes={Attribute(name=objectClass, values={'top', 'testClass'}), Attribute(name=srOptionalData, values={'{"@type":"java.util.HashMap"}'}), Attribute(name=Weight, values={'100'}), Attribute(name=Site, values={'1'}), Attribute(name=Ip, values={'10.0.0.1'}), Attribute(name=Date, values={'20190123104845.464Z'}), Attribute(name=Address, values={'test'}), Attribute(name=UniqueId, values={'abcdrfgtyhgf'})}, controls=**{EntryChangeNotificationControl(changeType=add, isCritical=false)})**

**Screenshots**
searchEntryReturned Bad response; searchEntry.getControls(); searchEntry=SearchResultEntry(dn='UniqueId=trfdecghtyfder,cn=Test,cn=1.0,cn=REST,cn=Test,cn=1.0.0,cn=abc,cn=com,cn=def,dc=new,dc=pa,dc=sw,dc=test,dc=se', messageID=3, attributes={Attribute(name=objectClass, values={'top', 'testClass'}), Attribute(name=srOptionalData, values={'{"@type":"java.util.HashMap"}'}), Attribute(name=Weight, values={'100'}), Attribute(name=Site, values={'1'}), Attribute(name=Ip, values={'10.0.0.1'}), Attribute(name=Date, values={'20190123104845.464Z'}), Attribute(name=Address, values={'test'}), Attribute(name=UniqueId, values={'abcdrfgtyhgf'})}, controls={})

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/pull/37

**Comment by AdhavanM** [comment]
the patch #37

**Comment by AdhavanM** [comment]
is closed and delivered to master.

**Comment by vharseko** [comment]
sorry

**Comment by AdhavanM** [comment]
thanks ! Can you kindly let me know whan the patch or fix should be possible for the same ?

**Comment by vharseko** [comment]
merged 
https://github.com/OpenIdentityPlatform/OpenDJ/commit/a229c2ad7d088b3e7d87259521d967f861b1d056 , please check and close

**Comment by AdhavanM** [comment]
Thanks !

**Comment by AdhavanM** [comment]
Hope the fix will be part of OpenDJ 4.3.3 release .Kindly confirm.

**Comment by vharseko** [comment]
yes

**Comment by vharseko** [comment]
please check in 
https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.3.3
