### ISSUE TITLE
Control Panel: empty help URL values

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#384]
**Description**

From within the OpenDJ `control-panel`, when clicking "**Help -> Administration Guide**", the following error is thrown with a URL "template var" that seems to have not been populated:

> ```                                                                     
> Could not launch the web browser. You can copy and paste the following
> URL manually into your web browser: ${docGuideAdminUrl}
> ```

Similarly, when visiting "**Help -> Documentation Wiki**", the following error is thrown:

> ```                                                                     
> Could not launch the web browser. You can copy and paste the following
> URL manually into your web browser: ${docWikiUrl}
> ```    

Note that I have not taken any steps to configure an appropriate browser to open, so for all I know that is my fault by virtue of missing configuration directives.

**I am, however, concerned about the unfilled `$` vars**, which I'm assuming should be referencing online resources.  Had my browser actually opened, its unlikely a subsequent GET request would have worked, given the content of the "link" 😃 

While I have only tested this using OpenDJ **4.6.5**, I do not see any mention of these variables in your **4.7.0** change log.  If I am mistaken, and you've already resolved this issue, feel free to close the ticket.

**Comment by vharseko** [comment]
fixed in [4.8.0](https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.8.0)
