### ISSUE TITLE
dsconfig --help options inconsistent

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#394]
**Describe the bug**

Per the OpenDJ admin guide, Section 2:

  - `dsconfig --help-all` (Display all subcommands)
  - `dsconfig --help-core-server` ( Display subcommands relating to core server)
  - `dsconfig --help-database` ( Display subcommands relating to caching and back-ends)
  - `dsconfig --help-logging` ( Display subcommands relating to logging)
  - `dsconfig --help-replication` ( Display subcommands relating to replication)
  - `dsconfig --help-security` ( Display subcommands relating to authentication and authorization)
  - `dsconfig --help-user-management` ( Display subcommands relating to user management)

... in addition to ...

> For help with individual subcommands, either use `dsconfig subcommand --help`, or start dsconfig in interactive mode, without specifying a subcommand.

Observe my command history

```
$ sudo ./bin/dsconfig replication --help
An error occurred while parsing the command-line arguments: The provided argument "replication" is not recognized

See "dsconfig --help" to get more usage help

$ sudo ./bin/dsconfig database --help
An error occurred while parsing the command-line arguments: The provided argument "database" is not recognized

See "dsconfig --help" to get more usage help
```

On the other hand, if I try:

```
$ sudo ./bin/dsconfig --help-database
$ sudo ./bin/dsconfig --help-replication
```

Here, I _do_ get output ... but its identical to simply using `--help`.  In fact all of the `--help-<subcommand>` options behave in a similar way.

If I had to guess, I'd say the global (top level) option list is occluding or shadowing the more specific subsections.

Thank you 😃 

Jesse Coretta

**Comment by vharseko** [comment]
workaround :)  https://doc.openidentityplatform.org/opendj/man-pages/#dsconfig-subcommands-ref

**Comment by JesseCoretta** [comment]
> workaround :) https://doc.openidentityplatform.org/opendj/man-pages/#dsconfig-subcommands-ref

Thank you!

May I ask -- is this workaround of a temporary nature, or will the `dsconfig --help` options be deprecated at some point in the future?

**Comment by JesseCoretta** [comment]
OK, then it sounds as if its simply a matter of stale information, as I copied those *incorrect* commands directly from OpenDJ terminal output.  Thank you for clarifying @vharseko 

I'd like to ask -- is the OpenDJ project looking for any volunteers to help with this sort of thing (document review, various levels of Q/A, subject matter expertise, etc.)?

If so, I'd like to formally offer my services to this project.  Please let me know how I can help 😃 

Jesse
