### ISSUE TITLE
DOC REVIEW: Syntax error and comments on dsconfig-driven ACI interaction

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#400]
### Page 60, Example 5.2, Block 2

```
$ dsconfig \
  set-access-control-handler-prop \
  --remove global-aci:\(targetattr!=\"userPassword\|\|authPassword\|\|changes\|\
  \|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\
  \|newSuperior\|\|deleteOldRDN\|\|targetEntryUUID\|\|changeInitiatorsName\|\
  \|changeLogCookie\|\|includedAttributes\"\)\(version\ 3.0\;\ acl\ \"Anonymous\
  \ read\ access\"\;\ allow\ \(read,search,compare\)\
  \ userdn=\"ldap:///anyone\"\;\)\
  --hostname opendj.example.com \
  --port 4444 \
  --bindDN cn=Directory\ Manager \
  --bindPassword password \
  --trustAll \
  --no-prompt
```

Since the "`!`" character (at "`\(targetattr=!...`"), does not reside within quotation, it needs to be ESCAPED as is done for "`(`", "`)`", "` `" and "`|`" characters, else you will suffer command interpretation errors following an unsuspecting copy/pasta:

```
An error occurred while parsing the command-line arguments: The provided
argument " " is not recognized

See "dsconfig --help" to get more usage help

set-access-control-handler-prop: command not found
--remove: command not found
|newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName|: command not found
bash:  userdn="ldap:///anyone";) : No such file or directory
--hostname: command not found
--port: command not found
--bindDN: command not found
--bindPassword: command not found
--trustAll: command not found
--no-prompt: command not found
```

Taking all of this into account, a near-identical command sequence which worked was:

```
/opt/opendj/bin/dsconfig \
set-access-control-handler-prop \
--remove global-aci:\(targetattr\!=\"userPassword\|\|authPassword\|\|changes\|\
\|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\
\|newSuperior\|\|deleteOldRDN\|\|targetEntryUUID\|\|changeInitiatorsName\|\
\|changeLogCookie\|\|includedAttributes\"\)\(version\ 3.0\;\ acl\ \"Anonymous\
\ read\ access\"\;\ allow\ \(read,search,compare\)\
\ userdn=\"ldap:///anyone\"\;\)\
--hostname=opendj.example.com \
--port=4444 \
--bindDN=cn=Directory\ Manager \
--bindPassword=password \
--trustAll \
--no-prompt
```

... which includes the escaped "!" fix AND the use of "=" operators in consistent fashion.

I was going to move on at this point, but something stopped me.

At the risk of sounding nit picky, these escape sequences are rather aggressive in practice.

While I acknowledge they are necessary given the limitations of interpreters like Bash, they introduce a higher risk syntax error. In a crisis situation, this can be ESPECIALLY unfortunate. 

Wondering if we should instead do this (which I tested for syntax):

```
$ dsconfig \
set-access-control-handler-prop \
--remove global-aci:'(targetattr!="userPassword||authPassword||changes||
changeNumber||changeType||changeTime||targetDN||newRDN||
newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName||
changeLogCookie||includedAttributes")(version 3.0; acl "Anonymous
 read access"; allow (read,search,compare) userdn="ldap:///anyone";)' \
--hostname=opendj.example.com \
--port=4444 \
--bindDN=cn=Directory\ Manager \
--bindPassword=password \
--trustAll \
--no-prompt
```

The above modified rule uses single apostrophe quoting for the ACI value itself and does away with ACI-specific escapes.

It does have the drawback of making the newline escapes inconsistent between flags and the multi-lined ACI, although I've never heard of anyone complaining because they had to escape fewer characters than before. The spirit of the rule is unchanged, thus:

> If the global-aci does not match the ACI exactly then the command fails to remove the value.

... should not apply here, but I recommend that this scenario be incorporated into unit tests, if applicable.

Be advised, my host does not have the above ACI, thus the following error was raised:

```
The value (targetattr!="userPassword||authPassword||changes||
changeNumber||changeType||changeTime||targetDN||newRDN||
newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName||
changeLogCookie||includedAttributes")(version 3.0; acl "Anonymous
read access"; allow (read,search,compare) userdn="ldap:///anyone";) for the
global-aci property does not exist
```

... which is the error that has appeared during all successful syntax-permutations of my test on this matter. I take this as a good omen, given that all of the ACI elements survived the alternative quoting method, and my login and network parameters were observed and honored as before.

Thanks! 😃

**Comment by JesseCoretta** [comment]
@maximthomas / @vharseko  -- do you have any thoughts on this?

**Comment by maximthomas** [comment]
Hi @JesseCoretta, 
Yes, you are right, your version is much easier to read due to the lack of escaping! 
Thanks!

**Comment by JesseCoretta** [comment]
@maximthomas - thanks.

The readability is just a nice side effect of the improvements.  Because the command **does not run** as-is due to an unescaped exclamation point -- I'd like to push this fix soon.  

But I recall that you said there was a switch to ASCII doc coming soon, and unless I'm mistaken, it sounded like it was a multi-step process.

Questions:

  - When would be a good date/time for me to proceed with this? Not sure if there is any work left for your doc switch
  - Do we have a new SoP for doc updates? I've only edited the XML source docs _once_ thus far, so please fill me in on any procedural changes

Jesse

**Comment by maximthomas** [comment]
Hi @JesseCoretta,

> What about the other issues -- for example, the --hostname weirdness? Shall I attempt to resolve these issues? If so I'll open another ticket

Yes, please, any contribution is highly appreciated.

> When would be a good date/time for me to proceed with the doc updates? Not sure if there is any work left for your migration ...

You can proceed any time you want, we have just migrated the documentation to the AsciiDoc format. There is not much work left (only minor improvements) so you can proceed with the new format at [opendj-doc-generated-ref/src/main/asciidoc](https://github.com/OpenIdentityPlatform/OpenDJ/tree/master/opendj-doc-generated-ref/src/main/asciidoc).

>Do we have a new SoP for doc updates? I've only edited the XML source docs once thus far, so please fill me in on any procedural changes

For a contributor's convenience, we are trying to make the contribution process as less formal as possible. So, you just clone the repository and make a pull request with the proposed changes.  
The only thing I should mention is that your contribution should be licensed under CDDL as the entire project.

**Comment by JesseCoretta** [comment]
Thank you @maximthomas. I did not want to step on your toes, that's why I asked.  I will proceed.

**Comment by JesseCoretta** [comment]
@maximthomas -- I am concerned there may have been some data that did not migrate via ASCIIDocs. The subject is the topic of this ticket.

Observe:

```
   <para>First, remove the <literal>global-aci</literal> attribute value that
   allows anonymous read access. Do not wrap the lines in the following 
   example if you use it as the basis for your script.</para>           
                                                                        
   <screen>$ dsconfig \                                                 
 set-access-control-handler-prop \                                      
 --remove global-aci:\(targetattr!=\"userPassword\|\|authPassword\|\|changes\|\
\|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\     
\|newSuperior\|\|deleteOldRDN\|\|targetEntryUUID\|\|changeInitiatorsName\|\
\|changeLogCookie\|\|includedAttributes\"\)\(version\ 3.0\;\ acl\ \"Anonymous\
\ read\ access\"\;\ allow\ \(read,search,compare\)\                     
\ userdn=\"ldap:///anyone\"\;\)\                                        
 --hostname opendj.example.com \                                        
 --port 4444 \                                                          
 --bindDN cn=Directory\ Manager \                                       
 --bindPassword password \                                              
 --trustAll \                                                           
 --no-prompt</screen> 
```

I see that in some cases, certain commands have been broken down ("compartmentalized"), e.g.:

```
a|`(targetattr!="userPassword\|\|authPassword\|\|debugsearchindex\|\|changes\|\|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\|newSuperior\|\|deleteOldRDN")(version 3.0; acl "Anonymous read access"; allow (read,search,compare) userdn="ldap:///anyone";)
```

... and while I thought that's all that changed, I am now realizing that the rule I sought to edit **definitely** did not make it over.  See the "`targetEntryUUID`" attribute in the previous `dsconfig` command? It is missing in ASCIIDoc, as is the preceding paragraph.

```
## Recursive, case INSENSITIVE grep for "targetEntryUUID"
$ ~/dev/opendj/jesseFork/OpenDJ/opendj-doc-generated-ref/src/main/asciidoc$ grep -ri targetEntryUUID
admin-guide/chap-replication.adoc:targetEntryUUID: 90c714f7-486b-4d47-9409-b44d19dea31e
admin-guide/chap-replication.adoc:targetEntryUUID: 6b22440a-76d0-4031-94b7-35b1d86f067e
admin-guide/chap-replication.adoc:targetEntryUUID: fc252fd9-b982-3ed6-b42a-c76d2546312c
```
... that is **definitely** not the match we were looking for.

And yet, if I hop-up one level and re-run the same **`grep`** sequence to include the previous `docbkx` file structure:

``
docbkx/admin-guide/chap-privileges-acis.xml: \|newSuperior\|\|deleteOldRDN\|\|targetEntryUUID\|\|changeInitiatorsName\|\
```

Therefore, I am **very uncomfortable** proceeding with these changes if I have reason to believe the new document system has "gaps".  Please confirm.

Jesse

**Comment by maximthomas** [comment]
Hi @JesseCoretta,
I understand your concern. 

The documentation has been migrated from the most recent source code to be more aligned with the most recent OpenDJ version.

As for your example, it was moved to the captured-global-aci-edits.sh script file.

```

[source, console]
----
$ dsconfig \
 --port 4444 \
 --hostname opendj.example.com \
 --bindDN "cn=Directory Manager" \
 --bindPassword password \
 --commandFilePath /tmp/captured-global-aci-edits.sh

# The dsconfig command runs interactively.

# Edit Access Control Handler, global-aci attributes replacing
# userdn="ldap:///anyone" (anonymous) with userdn="ldap:///all" (authenticated)
# in "Anonymous read access" and "User-Visible Operational Attributes" ACIs.

# To make this change, you first remove the existing values,
# then add the edited values, and finally apply the changes.
----
```

The file contents:
```bash
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions Copyright [year] [name of copyright owner]".
#
# Portions Copyright 2015 ForgeRock AS.

# Captured dsconfig command to replace anonymous read access with authenticated access.
# Edit this script to match your deployment.
#
# This command does not affect global-aci properties allowing anonymous access
# to read the root DSE and to read directory schema definitions,
# nor to use selected LDAP controls and extended operations.
#
# This command works against a server built following the changes introduced
# in http://sources.forgerock.org/changelog/opendj?cs=9325.
# If the global-aci settings are different on your OpenDJ server,
# generate this script for that server as described in the documentation.
#
dsconfig set-access-control-handler-prop \
          --remove global-aci:\(targetattr!=\"userPassword\|\|authPassword\|\|debugsearchindex\|\|changes\|\|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\|newSuperior\|\|deleteOldRDN\"\)\(version\ 3.0\;\ acl\ \"Anonymous\ read\ access\"\;\ allow\ \(read,search,compare\)\ userdn=\"ldap:///anyone\"\;\) \
          --remove global-aci:\(targetattr=\"createTimestamp\|\|creatorsName\|\|modifiersName\|\|modifyTimestamp\|\|entryDN\|\|entryUUID\|\|subschemaSubentry\|\|etag\|\|governingStructureRule\|\|structuralObjectClass\|\|hasSubordinates\|\|numSubordinates\"\)\(version\ 3.0\;\ acl\ \"User-Visible\ Operational\ Attributes\"\;\ allow\ \(read,search,compare\)\ userdn=\"ldap:///anyone\"\;\) \
          --add global-aci:\(targetattr!=\"userPassword\|\|authPassword\|\|debugsearchindex\|\|changes\|\|changeNumber\|\|changeType\|\|changeTime\|\|targetDN\|\|newRDN\|\|newSuperior\|\|deleteOldRDN\"\)\(version\ 3.0\;\ acl\ \"Authenticated\ read\ access\"\;\ allow\(read,search,compare\)\ userdn=\"ldap:///all\"\;\) \
          --add global-aci:\(targetattr=\"createTimestamp\|\|creatorsName\|\|modifiersName\|\|modifyTimestamp\|\|entryDN\|\|entryUUID\|\|subschemaSubentry\|\|etag\|\|governingStructureRule\|\|structuralObjectClass\|\|hasSubordinates\|\|numSubordinates\"\)\(version\ 3.0\;\ acl\ \"User-Visible\ Operational\ Attributes\"\;\ allow\(read,search,compare\)\ userdn=\"ldap:///all\"\;\) \
          --hostname opendj.example.com \
          --port 4444 \
          --trustStorePath /path/to/opendj/config/admin-truststore \
          --bindDN cn=Directory\ Manager \
          --bindPassword ****** \
          --no-prompt

```          

I'll add the missing file to the repository as soon as possible.

There could be some gaps in the new AsciiDoc documentation. If you see any, please let us know so we can eliminate the gaps. 

You can still edit the DocBook format, and we will migrate your changes to the AsciiDoc.

Thank you!

**Comment by JesseCoretta** [comment]
Ah, good.  I am relieved.  I will do as you suggest and edit the XML form shortly.

Thank you for the clarification

**Comment by JesseCoretta** [comment]
> @JesseCoretta please check changes in new source format [asciidoc](https://github.com/OpenIdentityPlatform/OpenDJ/tree/master/opendj-doc-generated-ref/src/main/asciidoc/admin-guide)
> 
> published https://doc.openidentityplatform.org/opendj/

@vharseko (replying here instead of the merged ticket for visibility)

Are you saying @maximthomas's comment no longer applicable?

> You can still edit the DocBook format, and we will migrate your changes to the AsciiDoc.

I ask because I'm about 99% through the build with the changes as of this moment, and the change itself is quite small  ...

**Comment by maximthomas** [comment]
Of course, it is better to edit the docs in the AsciiDoc format, but if there are some gaps or you have a work in progress, you can proceed with the the DocBook format to align later with AsciiDoc.

**Comment by maximthomas** [comment]
The DocBook documentation is currently deprecated and all new changes should be made in the AsciiDoc.

**Comment by JesseCoretta** [comment]
Excellent. The build just finished and rendered as expected, so I'll be making a PR momentarily

**Comment by JesseCoretta** [comment]
OK, I guess silence is golden :).  PR submitted.
