### ISSUE TITLE
Minor DIT content rule formatting issue

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#404]
**Describe the bug**

Consider the following fictional DIT content rule in which the `AUX` clause has been populated with more than one AUXILIARY class:

```
dITContentRules: ( 2.16.840.1.113730.3.2.2
          NAME 'inetContent'
          AUX ( posixAccount 
              $ shadowAccount )
          MUST ( o
               $ employeeNumber
               $ manager )
          MAY ( mail
              $ displayName
              $ jpegPhoto
              $ givenName
              $ userCertificate )
          NOT ( carLicense
              $ audio
              $ homePostalAddress ) )
```

... even if formatted differently, such as having `AUX` only occupy a single line:

`AUX ( posixAccount $ shadowAccount )`

... when queried through an LDAP Search operation via the `cn=schema` context, the `AUX` value is missing the leading inner parenthetical SPACE pad during presentation:

```
$ ldapsearch -xb cn=schema -s base dITContentRules

# schema
dn: cn=schema
dITContentRules: ( 2.16.840.1.113730.3.2.2 NAME 'inetContent' AUX (posixAccount $ shadowAccount ) MUST ( o $ employeeNumber $ manager ) MAY ( mail $ displayName $ jpegPhoto $ givenName $ userCertificate ) NOT ( carLicense $ audio $ homePostalAddress ) X-SCHEMA-FILE '99-user.ldif' )
```

So that it's easier to read, let's focus on the specific clause in question:

`AUX (posixAccount $ shadowAccount )`

... whereas it should read:

```
AUX ( posixAccount $ shadowAccount )
     ^
   SPACE ADDED   
```

## Fix

I believe the problem originates at line 690 in `opendj-core/src/main/java/org/forgerock/opendj/ldap/schema/DITContentRule.java`:

```
                buffer.append(" AUX (");
```

... should instead be ...

```
                buffer.append(" AUX ( ");
```

**Comment by JesseCoretta** [comment]
Testing this fix today

**Comment by maximthomas** [comment]
Hi @JesseCoretta! 
Thank you very much for your contributions! Currently, we are migrating the documentation to the [Aciiidoc](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) format. It will take some time, approx 2-3 days. Then I'll let you know where the documentation is, so you can edit it in your fork and create a pull request.

**Comment by maximthomas** [comment]
As an alternative, you could modify DocBook sources https://github.com/OpenIdentityPlatform/OpenDJ/tree/master/opendj-doc-generated-ref/src/main/docbkx. We will migrate your changes to the AsciiDoc format later.

**Comment by JesseCoretta** [comment]
> Hi @JesseCoretta! Thank you very much for your contributions!

Oh I'm just getting warmed-up! And **thank you** for letting me join this team @maximthomas. 😃 

> As an alternative, you could modify DocBook sources https://github.com/OpenIdentityPlatform/OpenDJ/tree/master/opendj-doc-generated-ref/src/main/docbkx. We will migrate your changes to the AsciiDoc format later.

This option seems easiest, since I figure you guys want to review my work and those were the exact files I modified. 

Specifically:

 - `opendj-doc-generated-ref/src/main/docbkx/admin-guide/chap-connection-handlers.xml`
   - Addresses #397
 - `opendj-doc-generated-ref/src/main/docbkx/admin-guide/chap-privileges-acis.xml` 
   - Addresses #398
   - Addresses #399
 - `opendj-doc-generated-ref/src/main/docbkx/admin-guide/chap-schema.xml`
   - Addresses #403

Screenshots (or PDF excerpts) are available in those issues for your review.  Later today I'll do a proper PR via fork.

Thank you
