### ISSUE TITLE
javadoc tag warnings

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#424]
Not sure if this has anything to do with the asciidoc errors, but I am creating this ticket for tracking.

Log file attachment: [javadoc_warn.txt](https://github.com/user-attachments/files/17265116/javadoc_warn.txt)

**Comment by maximthomas** [comment]
@JesseCoretta these messages are not related to the AsciiDoc. They appear when HTML symbols from javadoc are not escaped. This potentially could cause bad javadoc HTML generation.
Thanks for pointing out.

**Comment by JesseCoretta** [comment]
> @JesseCoretta these messages are not related to the AsciiDoc. They appear when HTML symbols from javadoc are not escaped. This potentially could cause bad javadoc HTML generation. Thanks for pointing out.

No problem -- I wrongly assumed it was XML tag issues from the old format.
