### ISSUE TITLE
RFC 3672 / X.501 subentry violation: Entry is invalid according to the server schema because there is no DIT structure rule that applies to that entry, but there is a DIT structure rule for the parent entry

### ISSUE THREAD

**Issue by JesseCoretta** [OpenIdentityPlatform/OpenDJ#425]
Creating issue per request of @vharseko.

**Describe the bug**

From co-author of [RFC 3672](https://datatracker.ietf.org/doc/html/rfc3672):

> "Although subentry and subentryNameForm are specified using the notation of
> clause 13, subentries are not regulated by DIT structure or DIT content rules."
> 
> An LDAP implementation that requires a DIT structure rule for subentries is not
> conformant with RFC 3672. The administrativeRole attribute of the superior entry
> governs the placement of subentries.
> 
> Section 14.2.2 also defines a subentry name form, which you could reproduce instead,
> but additionally states that:
> 
> "No other name form shall be used for subentries."

**To Reproduce**

  - Configure name forms and DIT structure rules. As I have stated repeatedly, any name forms and structure rules would suffice.
```
nameForms: ( 1.3.6.1.1.2.1
          NAME 'domainNameForm'
          OC domain
          MUST dc
          X-ORIGIN 'RFC2377' )
##
nameForms: ( 1.3.6.1.4.1.56521.999.2.7.2
          NAME 'ouForm'
          OC organizationalUnit
          MUST ou
          X-ORIGIN 'fake name form' )
##
dITStructureRules: ( 20
          NAME 'rootSuffixStructure'
          FORM domainNameForm )
##
dITStructureRules: ( 21
          NAME 'ouStructure'
          FORM ouForm
          SUP 20 )
##
``` 

  - Try to create a subentry -- **naming violation 64** is raised -- there should be _NO_ error
```
$ ldapadd -D "cn=Directory Manager" -w secret -x                        
                                                                        
dn: cn=test-subentry,ou=Accounts,dc=example,dc=com                      
objectClass: top                                                        
objectClass: extensibleObject                                           
objectClass: subentry                                                   
objectClass: collectiveAttributeSubentry                                
subtreeSpecification: {}                                                
                                                                        
adding new entry "cn=test-subentry,ou=Accounts,dc=example,dc=com"       
ldap_add: Naming violation (64)                                         
        additional info: Entry cn=test-subentry,ou=Accounts,dc=example,dc=com is invalid according to the server schema because there is no DIT structure rule that applies to that entry, but there is a DIT structure rule for the parent entry ou=Accounts,dc=example,dc=com
```

  - Create a subentry name form and structure rule. For the name form, use "cn" as MUST clause, "subentry" as OC clause.

```
## This is extracted from X.501.
nameForms: ( 2.5.15.16                                                  
          NAME 'subentryNameForm'                                       
          DESC 'X.501, cl. 14.2.2: the Subentry name form'              
          OC subentry                                                   
          MUST cn )                                                     

## This is manually composed, not derived from X.501 or any standar.d
dITStructureRules: ( 177                                              
          NAME 'subentryStructure'                                    
          FORM subentryNameForm                                       
          SUP ( 20 21 ) )
```

  - Restart service

  - Retry operation, no error:

```
$ ldapadd -D "cn=Directory Manager" -w secret -x                        
                                                                        
dn: cn=test-subentry,ou=Accounts,dc=example,dc=com                      
objectClass: top                                                        
objectClass: extensibleObject                                           
objectClass: subentry                                                   
objectClass: collectiveAttributeSubentry                                
subtreeSpecification: {}                                                
                                                                        
adding new entry "cn=test-subentry,ou=Accounts,dc=example,dc=com"
```

**Synopsis**

The name form in [ITU-T Rec. X.501 14.2.2](https://www.itu.int/rec/T-REC-X.501) is the only valid name form for this function.  It should not be necessary for users to manually solve this issue, as demonstrated above, by creating a name form and DIT structure rule. Instead, the name form should be built in, and no DIT structure rule should be needed

**Confirmation**
This has been **confirmed** by the co-author, and has been **formalized** in an [INFORMATIONAL I-D](https://datatracker.ietf.org/doc/html/draft-coretta-ldap-subnf), which has also been vetted by the same author. The I-D does not provide any new functionality, rather it merely talks about THIS ISSUE and offers commentary on how it should be fixed.

**Comment by vharseko** [comment]
👍  @JesseCoretta  please provide test schema and test data for reproduce this issue

**Comment by JesseCoretta** [comment]
@vharseko ... see below.

## Schema

Note that depending on your test server, you may need to create superior structure rules. If you require inspiration, see [RFC 2377](https://datatracker.ietf.org/doc/html/rfc2377) for popular name forms upon which such structure rules may be based.  Or you can just invent your own, it does not matter.

```
nameForms: ( 2.5.15.16
          NAME 'subentryNameForm'
          DESC 'X.501, cl. 14.2.2: the Subentry name form'
          OC subentry
          MUST cn )

## Uncomment this AFTER your first (failed) ldapadd attempt
# dITStructureRules: ( 177                                               
#           NAME 'subentryStructure'                                     
#           FORM subentryNameForm                                            
#           SUP ( 150 151 ) )
```
## Test Data

DIT content that corresponds to the above schema definitions (you can provide your own if you prefer):

```
dn: dc=example,dc=com
objectClass: top
objectClass: domain
dc: example

dn: ou=Accounts,dc=example,dc=com
objectClass: top
objectClass: organizationalUnit
ou: Accounts
```

Here is a basic `subentry`, but **any** `subentry` would do:

```
$ ldapadd -D "cn=Directory Manager" -w secret -x

dn: cn=test-subentry,ou=Accounts,dc=example,dc=com
objectClass: top
objectClass: extensibleObject
objectClass: subentry
objectClass: collectiveAttributeSubentry
subtreeSpecification: {}

adding new entry "cn=test-subentry,ou=Accounts,dc=example,dc=com"
ldap_add: Naming violation (64)
	additional info: Entry cn=test-subentry,ou=Accounts,dc=example,dc=com is invalid according to the server schema because there is no DIT structure rule that applies to that entry, but there is a DIT structure rule for the parent entry ou=Accounts,dc=example,dc=com
```
Note that the error itself doesn't matter beyond the fact that there should be NO error for subentry creation or relocation.

UNCOMMENT the above `dITStructureRules` definition and (if need be) restart OpenDJ.

Second `ldapadd` attempt (success):

```
$ ldapadd -D "cn=Registration Authority" -w secret -x
dn: cn=test-subentry,ou=Accounts,dc=example,dc=com
objectClass: top
objectClass: extensibleObject
objectClass: subentry
objectClass: collectiveAttributeSubentry
subtreeSpecification: {}

adding new entry "cn=test-subentry,ou=Accounts,dc=example,dc=com"
```
## Synopsis

Subentries should never be subject to DIT structure rule influence. It should not be necessary for users to add a subentry name form and DIT structure rule. The *official* X.501 name form is the only name form that should govern subentries, and it is normally expected to be **internally enforced**.  It is up to us (the maintainers) as to whether the X.501 name form is visible in the subschema.  The only requirement is that **_only_** CN is used as the RDN attribute for `subentry` instances; **no other type is permitted.**

See [Section 3 of my I-D for commentary on how we MIGHT solve this](https://datatracker.ietf.org/doc/html/draft-coretta-ldap-subnf#section-3).

Note this information is NOT specific to OpenDJ, rather any LDAP vendor afflicted with this bug would be a suitable audience member.

Please see me if you have any questions or need implementation guidance.

Jesse

**Comment by JesseCoretta** [comment]
Also @vharseko ...  consider mitigating user attempts to add **ANY** `subentry`-focused name form or DIT structure rule.

For compatibility reasons, Section 3 of my I-D advises that such attempts should trigger a non-fatal warning, while the erroneous definitions should be silently discarded.  The attempt need not stop server initialization.

**Comment by vharseko** [comment]
please edit issue body (To Reproduce) with test case

**Comment by JesseCoretta** [comment]
> please edit issue body (To Reproduce) with test case

Please elaborate.

**Comment by JesseCoretta** [comment]
@vharseko ... may I ask, do you have a particular strategy in mind?

The test information above merely proves my assertion, but as you said before, there is more than one way to a resolution.  Interested in your current thought process.

**Comment by vharseko** [comment]
we need to reproduce and research the problem

**Comment by JesseCoretta** [comment]
> we need to reproduce and research the problem

Obviously.  Not what I was asking, but nevermind.

**Comment by JesseCoretta** [comment]
@vharseko 👍🏻 .. just waiting for the Ubuntu builds.  Will advise, thanks! 😃

**Comment by JesseCoretta** [comment]
@vharseko -- we have good and bad news.

The good news is that subentries no longer require name forms and DIT structure rules to work. 🎆 🥳 

The bad news is that invalid subentries are allowed:

```
$ ldapadd -c -D "cn=Registration Authority" -w secret -x
dn: o=subentry,ou=People,dc=example,dc=com
objectClass: subentry
objectClass: extensibleObject
objectClass: collectiveAttributeSubentry
subtreeSpecification: {}
cn: subentry

adding new entry "o=subentry,ou=People,dc=example,dc=com"
```

The above RDN should never be possible.  This is the main point of my [Internet-Draft](https://datatracker.ietf.org/doc/html/draft-coretta-ldap-subnf), in that only one (1) name form should be used (thus, only CN should be allowed).  This is also confirmed in X.501 clause 14.2 and 14.2.2.

When I asked for your plans in my original bug report, this is why I was asking -- would we hard code the "essence" of X.501's subentries name form into our package, **OR** would we literally include that name form as a built-in schema definition?  That was all I meant.

Furthermore, the name form is shown in both of those documents because it wants to convey that only a single CN is permitted for subentries as the RDN.  In other words:

  - `o=subentry,...` ❌  (i.e.: ANYTHING that is not `cn`, or `2.5.4.3`)
  - `cn=subentry+cn=othername,...` ❌
  - `cn=subentry,...` ✔️

Additionally, the package should REJECT (with a warning only) any attempt to include a name form that bears an `OC` clause value of `subentry`.

**Comment by vharseko** [comment]
you probably didn't fully describe the test conditions

by default any form for **OC subentry** is possible     
but if **OC subentry MUST cn** is specified:
```
nameForms: ( 2.5.15.16                                                  
          NAME 'subentryNameForm'                                       
          DESC 'X.501, cl. 14.2.2.2: the Subentry name form'              
          OC subentry                                                   
          MUST cn )                                                     

dITStructureRules: ( 177                                              
          NAME 'subentryStructure'                                    
          FORM subentryNameForm                                       
          SUP ( 20 21 ) )
```

sample

```
TestCaseUtils.addEntry(
      “dn: o=subentry,ou=Accounts,dc=example,dc=com”,
              “objectClass: subentry”,
              “objectClass: extensibleObject”,
              “objectClass: collectiveAttributeSubentry”,
              “subtreeSpecification: {}”,
              “cn: subentry”
      );
```

get errror

Entry o=subentry,ou=Accounts,dc=example,dc=com violates the Directory Server schema configuration because its RDN does not contain attribute cn that is required by name form subentryNameForm

**Comment by JesseCoretta** [comment]
@vharseko, yeah I think it comes down to some communication difficulties that seem to be recurring.  I've just about run out of ideas as to how I can help in that regard.

> you probably didn't fully describe the test conditions

Again, this is why I wanted to _talk_ about the issue.  I don't feel like I got the chance to really participate effectively.  Its unfortunate, since I'm only trying to help you.

With that said, what exactly would you like me to do?

**Comment by maximthomas** [comment]
Hi @JesseCoretta, if there is no DIT structure rule for subentries, the name form should not be controlled for these subentries.
To implement 14.2.2 as you mentioned in the issue description, it should be defined _explicitly_, and be obvious for users.

**Comment by JesseCoretta** [comment]
@maximthomas  -- that is precisely the answer I wanted over a week ago, thank you.

So, the name form from X.501 clause 14.2.2 will will be added to our schema as a built-in definition. This would solve the issue originally reported, as well as the obvious flaws identified earlier. 

Agreed everyone?

**Comment by maximthomas** [comment]
@JesseCoretta I think implementing the "essense" of the name form without the need for a DIT structure rule and enforcing the private rules are not the best approaches, because they look like a hidden magic and could break existing OpenDJ instances.

I think a DIT structure rule should be set by users themselves, and this approach should be included in the OpenDJ documentation.

**Comment by vharseko** [comment]
confusion over **explicit** core schema rule
```
objectClasses: ( 2.5.17.0 NAME 'subentry'
  DESC 'LDAP Subentry class' SUP top STRUCTURAL MUST ( cn $
  subtreeSpecification ) X-ORIGIN 'RFC 3672' )
```
and **implicit** DIT RDN control 
```
nameForms: ( 2.5.15.16                                                  
          NAME 'subentryNameForm'                                       
          DESC 'X.501, cl. 14.2.2.2: the Subentry name form'              
          OC subentry                                                   
          MUST cn )                                                     

dITStructureRules: ( 177                                              
          NAME 'subentryStructure'                                    
          FORM subentryNameForm                                       
          SUP ( 20 21 ) )
```

**Comment by JesseCoretta** [comment]
> I think implementing the "essence" of the name form without the need for a DIT structure rule and enforcing the private rules are not the best approaches, because they look like a hidden magic and could break existing OpenDJ instances.

@maximthomas - this is helpful, thank you.  Understand that wasn't my idea.  It was a means to an end which some other vendors have adopted.  As far as ITU-T Rec. X.501 (the standard) is concerned, either is approach is acceptable.  Because I had no idea what would resonate with this team, I suggested both options without judgment.

> I think a DIT structure rule should be set by users themselves, and this approach should be included in the OpenDJ documentation.

I have no objection to that approach, sounds good.

**Comment by JesseCoretta** [comment]
@vharseko  - not sure if I am seeing exactly where the confusion is, but I'll try to clarify:

> confusion over **explicit** core schema rule
> 
> ```
> objectClasses: ( 2.5.17.0 NAME 'subentry'
>   DESC 'LDAP Subentry class' SUP top STRUCTURAL MUST ( cn $
>   subtreeSpecification ) X-ORIGIN 'RFC 3672' )
> ```

Well this is an object class -- it requires use of "cn", but this does not enforce the naming of the entry to use "cn".  The OC "MUST" and "MAY" clauses only relate to attributes present (or not) within the entry itself ... though this has no bearing on the RDN.  That's where name forms and structure rules come into play.

If you recall:

```
$ ldapadd -c -D "cn=Registration Authority" -w secret -x

dn: o=subentry,ou=People,dc=example,dc=com
objectClass: subentry
objectClass: extensibleObject
objectClass: collectiveAttributeSubentry
subtreeSpecification: {}
cn: subentry                                                 <-- this is all I had to do to satisfy the OC "MUST" clause
```

> and **implicit** DIT RDN control
> 
> ```
> nameForms: ( 2.5.15.16                                                  
>           NAME 'subentryNameForm'                                       
>           DESC 'X.501, cl. 14.2.2.2: the Subentry name form'              
>           OC subentry                                                   
>           MUST cn )                                                     
> 
> dITStructureRules: ( 177                                              
>           NAME 'subentryStructure'                                    
>           FORM subentryNameForm                                       
>           SUP ( 20 21 ) )
> ```

Well this is _explicit_, is it not?  We're explicitly referencing the ITU-T X.501 name form "subentryNameForm" with an explicit DIT structure rule.  Then again, maybe I am just not interpreting your comment correctly.

Granted, if we go with @maximthomas's suggestion, the structure rule would look different in every directory, based on the needs of the implementing user.  The name form, however, is a constant.

Also, not that it matters technically -- but it looks like an extra ".2" got placed in the name form "DESC" clause, thus:

`DESC 'X.501, cl. 14.2.2.2: the Subentry name form'`

... is actually ...

`DESC 'X.501, cl. 14.2.2: the Subentry name form'`

I verified it is correct in my paper and (at least) in the comment I made previously.
