### ISSUE TITLE
Error in wiki page Administration-Guide : no replication

### ISSUE THREAD

**Issue by ppbrown** [OpenIdentityPlatform/OpenDJ#44]
https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Administration-Guide

says

   To get started with replication, see Managing Data Replication.

but "Managing Data Replication" is an invalid reference

Apparently, it needs to be changed to an in-page reference, such as

Administration-Guide#chapter-8-managing-data-replication

but thats a bit ugly, particularly since there is no table of contents, so having
"Chapter 1,2,3,4,...8" seems a bit silly, in addition to the ugly anchor naming.

I get the sense that the wiki page may be auto-generated? Otherwise, I might volunteer to clear up some of the bad refs.

**Comment by vharseko** [comment]
@kurnysh please fix refs

**Comment by vharseko** [comment]
related https://github.com/OpenIdentityPlatform/OpenDJ/issues/25

**Comment by kurnysh** [comment]
Done
