### ISSUE TITLE
lack of documentation for "adminUID" in replication

### ISSUE THREAD

**Issue by ppbrown** [OpenIdentityPlatform/OpenDJ#45]
I'm trying to get replication working, and there's some crucial missing information.

https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Administration-Guide
8.3.1

has
dsreplication \
 enable \
 --adminUID admin \
 --adminPassword password 
  ...

but it doesnt mention what this "adminUID" is. 

This particularly confusing since pretty much anything else is done using
cn=Directory Manager
and there doesnt seem to be any mention of setting up this admin user, in the entire administration guide.
(or even what its purpose is)

I'd really like to get replication working!

**Comment by vharseko** [comment]
please check https://cdn.rawgit.com/wiki/OpenIdentityPlatform/OpenDJ/docbkx/webhelp/man-pages/dsreplication-1.html

**Comment by ppbrown** [comment]
Ah.. thank you for the reference to the manpage, which I didnt know about.
that being said.. I would say that the "bug" of lacking documentation in the above URL still exists.
It would still be nice for the administrators guide, to inform the new administrator, that this is a reference to an account that will be CREATED for you if it doesnt exist.
(if I'm reading the manual page right)
