### ISSUE TITLE
Opendj Install fails (Error Creating Base Entry) if running opendj in docker with volume

### ISSUE THREAD

**Issue by rKS2827** [OpenIdentityPlatform/OpenDJ#50]
**Describe the bug**
Opendj4.3.3 Install fails if running opendj in docker with volume

i.e 
docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v C:/Users/openidentityplatform/data:/opt/opendj/data  --name ldap-01 openidentityplatform/opendj 

i.e  Below is docker-compose file 
![image](https://user-images.githubusercontent.com/11499073/53039260-cff91800-34a4-11e9-9fb4-928a9619d48b.png)

Error Logs -

- category=QUICKSETUP seq=68 severity=WARNING msg=Error writing host name file: java.io.FileNotFoundException: /opt/opendj/config/hostname (No such file or directory)
- 
- [19/02/2019:13:48:47 +0000] category=QUICKSETUP seq=84 severity=WARNING msg=import-ldif error log: [19/02/2019:13:48:47 +0000] category=TOOLS seq=26 severity=SEVERE msg=An error occurred while attempting to process the LDIF import:  ThreadInterruptedException((JE 7.5.11) Environment must be closed, caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 7.5.11) /opt/opendj/data/db/userRoot java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.)
- [19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=85 severity=SEVERE msg=Error: Error Creating Base Entry.
- [19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=86 severity=SEVERE msg=Caught exception: Error Creating Base Entry.
- [19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=87 severity=SEVERE msg=Error installing.
[opendj-error-base.log](https://github.com/OpenIdentityPlatform/OpenDJ/files/2881492/opendj-error-base.log)

**To Reproduce**

- Create the directory - C:/Users/openidentityplatform/data
- Run  below command-
`docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v C:/Users/openidentityplatform/data:/opt/opendj/data  --name ldap-01 openidentityplatform/opendj 
`
-See error

**Expected behavior**
-opendj docker should start without error  and should able to mount volume for data persistance

However opendj docker container working as expected if we don't mount the volume.
i.e 
`docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 --name ldap-01 openidentityplatform/opendj `

**Screenshots**

![image](https://user-images.githubusercontent.com/11499073/53038834-aa1f4380-34a3-11e9-9a12-43b344a493b0.png)

**Desktop (please complete the following information):**
 - OS: Windows7
 - Opendj version 4..3.3

**Comment by maximthomas** [comment]
@rKS2827, hello, try this command, seems there's an issue with docker in Windows
```docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v //c/Users/openidentityplatform/data:/opt/opendj/data  --name ldap-01 openidentityplatform/opendj```

**Comment by rKS2827** [comment]
Thanks for quick response. But getting the same error. Please see below screenshot.
-Also, I can see data is getting created in the mounted local directory.

//c/Users/openidentityplatform/data . The only issue is not able to create base entry


![image](https://user-images.githubusercontent.com/11499073/53071788-429bdf00-3509-11e9-8245-e66d7446dc7a.png)

**Comment by rKS2827** [comment]
> @rKS2827, hello, try this command, seems there's an issue with docker in Windows
> `docker run -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v //c/Users/openidentityplatform/data:/opt/opendj/data --name ldap-01 openidentityplatform/opendj`


Thanks for quick response. But getting the same error. Please see below screenshot.
-Also, I can see data is getting created in the mounted local directory.

//c/Users/openidentityplatform/data . The only issue is not able to create base entry

![image](https://user-images.githubusercontent.com/11499073/53072103-2c425300-350a-11e9-9490-afd2639fb9e6.png)

**Comment by vharseko** [comment]
>[19/02/2019:13:48:00 +0000] category=QUICKSETUP seq=68 severity=WARNING msg=Error writing host name file: java.io.FileNotFoundException: /opt/opendj/config/hostname (No such file or directory)

why not /opt/opendj/data/config/hostname ?

**Comment by rKS2827** [comment]
> @rKS2827 сould you attach opendj setup log?
Please see attached logs -
[opendj-setup-error.log](https://github.com/OpenIdentityPlatform/OpenDJ/files/2883386/opendj-setup-error.log)

**Comment by rKS2827** [comment]
> > [19/02/2019:13:48:00 +0000] category=QUICKSETUP seq=68 severity=WARNING msg=Error writing host name file: java.io.FileNotFoundException: /opt/opendj/config/hostname (No such file or directory)
> 
> why not /opt/opendj/data/config/hostname ?

It's weird. It should create while installation of opendj .right?

**Comment by maximthomas** [comment]
@rKS2827 seems user `opendj` can't get permissions
There's a couple workarounds

**Comment by maximthomas** [comment]
@vharseko this command must be executed on the host machine, not in docker

**Comment by rKS2827** [comment]
> 1. ker with root user `docker run -u root -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v //c/Users/openidentityplatform/data:/opt/opendj/data --name ldap-01 openidentityplatform/opendj`

Thanks , I have tried  1st solution,but no luck .getting same error.  :(
1. docker run -u root -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v //c/Users/openidentityplatform/data:/opt/opendj/data --name ldap-01 openidentityplatform/opendj

**Comment by rKS2827** [comment]
> @rKS2827 seems user `opendj` can't get permissions
> There's a couple workarounds
> 
> 1. run docker with root user `docker run -u root -h ldap-01.domain.com -p 1389:1389 -p 1636:1636 -p 4444:4444 -v //c/Users/openidentityplatform/data:/opt/opendj/data --name ldap-01 openidentityplatform/opendj`
> 2. In Linux you can grant docker opendj user permissions to access host directory: `chown 1001:1001 ./data/`
Hi I have tried running container on linux environment (ubuntu) with root user ,but getting same error.

![image](https://user-images.githubusercontent.com/11499073/53078740-e5a92480-351a-11e9-836d-cd6565486357.png)

**Comment by maximthomas** [comment]
@rKS2827 please show output `docker image ls | grep openidentityplatform/opendj`

**Comment by rKS2827** [comment]
> @rKS2827 please show output `docker image ls | grep openidentityplatform/opendj`
Please see below 
![image](https://user-images.githubusercontent.com/11499073/53081010-f60fce00-351f-11e9-9018-524bf7f333a8.png)

**Comment by maximthomas** [comment]
@rKS2827 @vharseko, guys, FYI, seems there's an issue with Docker Toolbox based on VirtualBox (before Windows 10) shared volumes and the database engine. I've just tried to start OpenDJ in Docker in Windows 10 based on Hyper-V and everything works fine.

**Comment by rKS2827** [comment]
@maximthomas I have tried on  Ubuntu and getting the same error if I mount the directory.

**Comment by rKS2827** [comment]
@maximthomas I have tried on  Ubuntu and getting the same error if I mount the directory. I don't think the issue is specific to Docker Toolbox.

**Comment by maximthomas** [comment]
@rKS2827 the error in ubuntu in opendj-setup.log is the same? because I can't reproduce this problem in Ubuntu

**Comment by rKS2827** [comment]
@maximthomas Yes, error is same. 

![image](https://user-images.githubusercontent.com/11499073/53193025-f26e6b00-3635-11e9-9963-aebba5dc462f.png)

**Comment by maximthomas** [comment]
@rKS2827 I mean error in opendj-setup.log
```
[19/02/2019:13:48:47 +0000] category=QUICKSETUP seq=84 severity=WARNING msg=import-ldif error log: [19/02/2019:13:48:47 +0000] category=TOOLS seq=26 severity=SEVERE msg=An error occurred while attempting to process the LDIF import:  ThreadInterruptedException((JE 7.5.11) Environment must be closed, caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 7.5.11) /opt/opendj/data/db/userRoot java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.)
[19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=85 severity=SEVERE msg=Error: Error Creating Base Entry.
[19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=86 severity=SEVERE msg=Caught exception: Error Creating Base Entry.
[19/02/2019:13:48:48 +0000] category=QUICKSETUP seq=87 severity=SEVERE msg=Error installing.
```

**Comment by rKS2827** [comment]
@maximthomas  Yes ,error is same in the opendj-setup.log ,please see attached logs -

Also, there is one more error -Insufficient free memory (87222454 bytes) to perform the import.

=import-ldif error log: msg=An error occurred while attempting to process the LDIF import:  Insufficient free memory (87222454 bytes) to perform import. At least 87293952 bytes of free memory is required


[opendj-setup.log.txt](https://github.com/OpenIdentityPlatform/OpenDJ/files/2891028/opendj-setup.log.txt)

**Comment by maximthomas** [comment]
@rKS2827 
in previous log there is sleepycat error message
```
[19/02/2019:13:48:47 +0000] category=QUICKSETUP seq=84 severity=WARNING msg=import-ldif error log: [19/02/2019:13:48:47 +0000] category=TOOLS seq=26 severity=SEVERE msg=An error occurred while attempting to process the LDIF import:  ThreadInterruptedException((JE 7.5.11) Environment must be closed, caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 7.5.11) /opt/opendj/data/db/userRoot java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.)
```
but in the recent log there is memory error message
```
[21/02/2019:19:50:26 +0000] category=QUICKSETUP seq=83 severity=WARNING msg=import-ldif error log: [21/02/2019:19:50:26 +0000] category=TOOLS seq=25 severity=SEVERE msg=An error occurred while attempting to process the LDIF import:  Insufficient free memory (87222454 bytes) to perform import. At least 87293952 bytes of free memory is required
```
Try to increase memory and try again

**Comment by vharseko** [comment]
@maximthomas please test on Win7: add "install.loc" with R/W path  and R/O mode for install path

**Comment by maximthomas** [comment]
> please test on Win7: add "install.loc" with R/W path and R/O mode for install path

@vharseko @rKS2827  just tested this case and got no errors, OpenDJ works fine

**Comment by vharseko** [comment]
cannot reproduce without "docker on Win7"
cannot reproduce with 
- "docker on Win10"
- "docker on Mac"
- "docker on Linux"
- "Win7 without docker and data path reallocation"
