### ISSUE TITLE
OpenDJ DSML gateway gives 404 after installation

### ISSUE THREAD

**Issue by effad** [OpenIdentityPlatform/OpenDJ#57]
I've followed https://github.com/OpenIdentityPlatform/OpenDJ/wiki/Installation-Guide#to-install-opendj-dsml-gateway to install opendj-dsml-servlet-4.4.1.war on an Apache Tomcat/9.0.13.

Deployment worked, but when I open http://localhost:8080/opendj-dsml-servlet-4.4.1/ I only get 
HTTP Status 404 – Not Found
Type Status Report
Message /opendj-dsml-servlet-4.4.1/

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

1. Download opendj-dsml-servlet-4.4.1.war from https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.4.1
2. Deploy in Apache Tomcat 
3. Open URL /opendj-dsml-servlet-4.4.1/
4. HTTP Status 404 – Not Found

**Expected behavior**
Web application should open

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Comment by vharseko** [comment]
please add output 
```
bin/version.sh
```
and attach logs/catalina.out

**Comment by effad** [comment]
[catalina.2019-03-12.log](https://github.com/OpenIdentityPlatform/OpenDJ/files/2957290/catalina.2019-03-12.log)

I am afraid I don't quite understand what you mean with bin/version.sh.

As far as I can tell, there is no version.sh in tomcat under Fedora 29.

```
[rli@rlinux Downloads]$ rpm -ql tomcat  | grep version
[rli@rlinux Downloads]$ ```

As stated above I am using Fedora's Tomcat-9.0.13

**Comment by bugspencor** [comment]
The URL for directory operations would be http://localhost:8080/opendj-dsml-servlet-4.4.1/DSMLServlet in your case.

As far as I know opendj-dsml-servlet does not have a web-interface http://localhost:8080/opendj-dsml-servlet-4.4.1/ as some other Tomcat applications.

Configuration is done in the WEB-INF/web.xml file.

**Comment by vharseko** [comment]
thanks @bugspencor
