### ISSUE TITLE
Control panel  is still alive or to be removed in the future ?

### ISSUE THREAD

**Issue by shynome** [OpenIdentityPlatform/OpenDJ#65]
there are some issues:
https://bugster.forgerock.org/jira/browse/OPENDJ-2959
https://github.com/OpenIdentityPlatform/OpenDJ/issues/13

**Comment by vharseko** [comment]
still alive

**Comment by shynome** [comment]
My mistake, actually I want to know : Is still available in the future

**Comment by maximthomas** [comment]
@shynome, we don't have plans to remove Control Panel, it will available

**Comment by shynome** [comment]
@maximthomas Thanks your reply . 
the control panel (version: 4.4.1) on windows has problems , that make me stop use it. I will try to fix it , but I am a noop java developer. hope someone can fix it

**Comment by winklerd** [comment]
Fix for OPENDJ-2959 "Control panel Manage Entries window is broken"
/opendj-server-legacy/src/main/java/org/opends/guitools/controlpanel/ui/SimplifiedViewEntryPanel.java
[SimplifiedViewEntryPanel.zip](https://github.com/OpenIdentityPlatform/OpenDJ/files/3136204/SimplifiedViewEntryPanel.zip)
I'm not allowed to push a change to this repository, so find the file attached

**Comment by maximthomas** [comment]
@winklerd hi, you can create a fork of this repo, change files, then make pull request
