### ISSUE TITLE
Invalid Credentials error when using docker

### ISSUE THREAD

**Issue by PetroRudenko** [OpenIdentityPlatform/OpenDJ#69]
**Describe the bug**
I am trying to setup cluster (with simple replication) using docker containers .
Environment: 
   AWS EC2 
   3 instances with Centos 7
   Docker version 18.09.6, build 481bc77156

When I want to check replication status with command "dsreplication status" I get error "Invalid Credentials"

**To Reproduce**
1. Go to AWS management console and execute 3 EC2 instances with CentOS 7
2. Setup docker engine
3. Setup OpenDJ cluster:
   on every instance run command:
   docker run -d -h "$(hostname -f)" -p 1389:1389 -p 1636:1636 -p 4444:4444 -p 8989:8989 -e MASTER_SERVER=ip-192-168-1-1.ec2.internal -e BASE_DN="dc=ec2,dc=internal" -e ROOT_USER_DN="cn=Directory Manager" -e ROOT_PASSWORD=welcome -e OPENDJ_REPLICATION_TYPE=simple openidentityplatform/opendj

4. Then try to check replication status:
    connect to containers' shell with command:
       docker exec -it <container id> /bin/bash
    run command:
       /opt/opendj/bin/dsreplication status

5. As result I have the next:
  >>>> Specify OpenDJ LDAP connection parameters
  Directory server hostname or IP address [ip-192-168-1-14.ec2.internal]:
  Directory server administration port number [4444]:
  Global Administrator User ID [admin]:
  Password for user 'admin':
  The provided credentials are not valid in server
  ip-192-168-1-14.ec2.internal:4444.  Details: Invalid Credentials

**Expected behavior**
I expected to see replication status.

**Comment by maximthomas** [comment]
@PetroRudenko can you provide docker container logs?

**Comment by PetroRudenko** [comment]
@maximthomas 

--------------- docker1 log --------------------------------------
Instance data Directory is empty. Creating new DJ instance
BASE DN is dc=test,dc=org 
Password set to Welcome
Running /opt/opendj/bootstrap/setup.sh
Setting up default OpenDJ instance

Configuring Directory Server ..... Done.
Configuring Certificates ..... Done.
Creating Base Entry dc=test,dc=org ..... Done.
Starting Directory Server ......... Done.

To see basic server configuration status and configuration, you can launch
/opt/opendj/bin/status

Setting up replication from ip-192-168-1-208.ec2.internal to 192.168.1.208
172.21.0.2      ip-192-168-1-208.ec2.internal ip-192-168-1-208 
We are the master. Skipping replication setup to ourself
Server Run Status:        Started
OpenDJ is started

--------------- docker2 log --------------------------------------
Instance data Directory is empty. Creating new DJ instance
BASE DN is dc=test,dc=org
Password set to Welcome
Running /opt/opendj/bootstrap/setup.sh
Setting up default OpenDJ instance

Configuring Directory Server ..... Done.
Configuring Certificates ..... Done.
Creating Base Entry dc=test,dc=org ..... Done.
Starting Directory Server ......... Done.

To see basic server configuration status and configuration, you can launch
/opt/opendj/bin/status

Setting up replication from ip-192-168-1-48.ec2.internal to 192.168.1.208
replicate ENV vars:
HOSTNAME=ip-192-168-1-48
LDAPS_PORT=1636
ROOT_USER_DN=cn=Directory Manager
BASE_DN=dc=test,dc=org
CA_CERTIFICATES_JAVA_VERSION=20140324
PASSWORD=Welcome
PATH=/opt/opendj/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/opt/opendj
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=C.UTF-8
JAVA_VERSION=8u111
ADD_BASE_ENTRY=--addBaseEntry
ROOT_PASSWORD=Welcome
MASTER_SERVER=192.168.1.208
JAVA_DEBIAN_VERSION=8u111-b14-2~bpo8+1
HOME=/home/opendj
SHLVL=2
SECRET_VOLUME=
OPENDJ_USER=opendj
OPENDJ_SSL_OPTIONS=--generateSelfSignedCertificate
OPENDJ_REPLICATION_TYPE=simple
PORT=1389
_=/usr/bin/env
Will sleep for a bit to ensure master is up
Enabling Standart Replication...

Establishing connections ..... Done.
Checking registration information ..... Done.
Configuring Replication port on server ip-192-168-1-48.ec2.internal:4444 ..... Done.
Configuring Replication port on server 192.168.1.208:4444 ..... Done.
Updating replication configuration for baseDN dc=test,dc=org on server
ip-192-168-1-48.ec2.internal:4444 .....Done.
Updating replication configuration for baseDN dc=test,dc=org on server
192.168.1.208:4444 .....Done.
Updating registration configuration on server
ip-192-168-1-48.ec2.internal:4444 .....Done.
Updating registration configuration on server 192.168.1.208:4444 ..... Done.
Updating replication configuration for baseDN cn=schema on server
ip-192-168-1-48.ec2.internal:4444 .....Done.
Updating replication configuration for baseDN cn=schema on server
192.168.1.208:4444 .....Done.
Initializing registration information on server 192.168.1.208:4444 with the
contents of server ip-192-168-1-48.ec2.internal:4444 .....Done.
Initializing schema on server 192.168.1.208:4444 with the contents of server
ip-192-168-1-48.ec2.internal:4444 .....initializing replication
Server Run Status:        Started
OpenDJ is started

--------------- docker3 log --------------------------------------
Instance data Directory is empty. Creating new DJ instance
BASE DN is dc=test,dc=org
Password set to Welcome
Running /opt/opendj/bootstrap/setup.sh
Setting up default OpenDJ instance

Configuring Directory Server ..... Done.
Configuring Certificates ..... Done.
Creating Base Entry dc=test,dc=org ..... Done.
Starting Directory Server .......... Done.

To see basic server configuration status and configuration, you can launch
/opt/opendj/bin/status

Setting up replication from ip-192-168-1-27.ec2.internal to 192.168.1.208
replicate ENV vars:
HOSTNAME=ip-192-168-1-27
LDAPS_PORT=1636
ROOT_USER_DN=cn=Directory Manager
BASE_DN=dc=test,dc=org
CA_CERTIFICATES_JAVA_VERSION=20140324
PASSWORD=Welcome
PATH=/opt/opendj/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/opt/opendj
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
LANG=C.UTF-8
JAVA_VERSION=8u111
ADD_BASE_ENTRY=--addBaseEntry
ROOT_PASSWORD=Welcome
MASTER_SERVER=192.168.1.208
JAVA_DEBIAN_VERSION=8u111-b14-2~bpo8+1
HOME=/home/opendj
SHLVL=2
SECRET_VOLUME=
OPENDJ_USER=opendj
OPENDJ_SSL_OPTIONS=--generateSelfSignedCertificate
OPENDJ_REPLICATION_TYPE=simple
PORT=1389
_=/usr/bin/env
Will sleep for a bit to ensure master is up
Enabling Standart Replication...

Establishing connections ..... Done.
Checking registration information ..... Done.
Configuring Replication port on server ip-192-168-1-27.ec2.internal:4444 ..... Done.
Updating remote references on server 192.168.1.208:4444 ..... Done.
Updating replication configuration for baseDN dc=test,dc=org on server
ip-192-168-1-27.ec2.internal:4444 .....Done.
Updating replication configuration for baseDN dc=test,dc=org on server
192.168.1.208:4444 .....Done.
Updating registration configuration on server
ip-192-168-1-27.ec2.internal:4444 .....Done.
Updating registration configuration on server 192.168.1.208:4444 ..... Done.
Updating replication configuration for baseDN cn=schema on server
ip-192-168-1-27.ec2.internal:4444 .....Done.
Updating replication configuration for baseDN cn=schema on server
192.168.1.208:4444 .....Done.
Initializing registration information on server 192.168.1.208:4444 with the
contents of server ip-192-168-1-27.ec2.internal:4444 .....Done.
Initializing schema on server 192.168.1.208:4444 with the contents of server
ip-192-168-1-27.ec2.internal:4444 .....Done.

Replication has been successfully enabled.  Note that for replication to work
you must initialize the contents of the base DNs that are being replicated
(use dsreplication initialize to do so).

See /tmp/opendj-replication-8696622925195150649.log for a detailed log of this
operation.

initializing replication

Initializing base DN dc=test,dc=org with the contents from
ip-192-168-1-27.ec2.internal:4444:
1 entries processed (100 % complete).
Base DN initialized successfully.

See /tmp/opendj-replication-7565376814152592264.log for a detailed log of this
operation.

Server Run Status:        Started
OpenDJ is started

**Comment by maximthomas** [comment]
@PetroRudenko have you tried `admin` password same as `cn=Directory Manager` password?

**Comment by maximthomas** [comment]
@PetroRudenko hi, has your problem solved?

**Comment by volodyad** [comment]
Seems issue was similar to https://forum.forgerock.com/topic/dsreplication-failure/
We used ip address for MASTER_SERVER instead of hostname. It worked very unstable, with hostname all works fine.

**Comment by maximthomas** [comment]
@volodyad thanks for the hint! 
@PetroRudenko has your problem solved?
