### ISSUE TITLE
Unable to build OpenDJ tag 4.4.2 due to dependency error. 

### ISSUE THREAD

**Issue by arun1607** [OpenIdentityPlatform/OpenDJ#70]
Hi,

I am trying to build OpenDJ but it is failing due to below error:

**************************************** ERROR ******************************
[INFO] Scanning for projects...
Downloading from central: http://nexus.idmworks.net:8084/nexus/repository/maven-group/org/forgerock/commons/commons-bom/21.0.0-SNAPSHOT/maven-metadata.xml
Downloading from central: http://nexus.idmworks.net:8084/nexus/repository/maven-group/org/forgerock/commons/commons-bom/21.0.0-SNAPSHOT/commons-bom-21.0.0-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.forgerock.commons:commons-bom:pom:21.0.0-SNAPSHOT in central (http://nexus.idmworks.net:8084/nexus/repository/maven-group/) @ line 140, column 24
[ERROR] 'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 239, column 21
[ERROR] 'dependencies.dependency.version' for org.testng:testng:jar is missing. @ line 252, column 21
[ERROR] 'dependencies.dependency.version' for org.slf4j:slf4j-jdk14:jar is missing. @ line 258, column 21
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.forgerock.opendj:opendj-parent:4.4.2 (/Users/amitshrivastava/project_work/repository/OpenDJ/pom.xml) has 4 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.forgerock.commons:commons-bom:pom:21.0.0-SNAPSHOT in central (http://nexus.idmworks.net:8084/nexus/repository/maven-group/) @ line 140, column 24 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.assertj:assertj-core:jar is missing. @ line 239, column 21
[ERROR]     'dependencies.dependency.version' for org.testng:testng:jar is missing. @ line 252, column 21
[ERROR]     'dependencies.dependency.version' for org.slf4j:slf4j-jdk14:jar is missing. @ line 258, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**************************************** ERROR ******************************

I also tried to compile **commons-bom** repository but didn't find any **21.0.0-SNAPSHOT** version.

We want to embed OpenDJ in out application and for that I want to compile the OpenDJ repository.

Thanks in advance.

Regards,
Amit

**Comment by maximthomas** [comment]
@arun1607, Hi, have you build `OpenDJ/forgerock-parent` project?

**Comment by vharseko** [comment]
@arun1607  please check https://github.com/OpenIdentityPlatform/OpenDJ#how-to-build
