### ISSUE TITLE
Cannot open control panel on mac

### ISSUE THREAD

**Issue by volodyad** [OpenIdentityPlatform/OpenDJ#71]
Download source code from github

go to OpenDJ/opendj-server-legacy/resource/mac
Double click on ControlPanel
it says: "The application “ControlPanel” can’t be opened."
mac console error: 
(org.opends.guitools.controlpanel.ControlPanelLauncher.14844[80720]): Service exited with abnormal code: 1

Also tried to download from https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.3.1
go to bin folder 
mac console error: com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000004a.universalJavaApplicationStub[80493]): Service exited with abnormal code: 1

 - OS: macos Mojave 10.14.5
 - java version "1.8.0_144"

**Comment by vharseko** [comment]
please try unzip and install instance:
```bash
unzip ~/git/OpenIdentityPlatform/OpenAM/OpenDJ/opendj-server-legacy/target/package/opendj-4.4.3-SNAPSHOT.zip
opendj/setup 
open opendj/bin/ControlPanel.app
```
