### ISSUE TITLE
OpenDJ 4.4.2 and 4.4.3-SNAPSHOT build error

### ISSUE THREAD

**Issue by 13Homer** [OpenIdentityPlatform/OpenDJ#75]
When I trying build 4.4.2 or 4.4.3-SNAPSHOT using "mvn clean install -DskipTests=true" there is following error in module opendj-core (I've successfully built and install forgerock-parent):

> [ERROR] Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.6.1:check (mvn verify) on project opendj-core: Failed to build project for previous artifact: Some problems were encountered while processing the POMs:
> [ERROR] [ERROR] 'dependencies.dependency.version' for org.mockito:mockito-all:jar is missing. @ org.forgerock.opendj:opendj-sdk-parent:[unknown-version], /home/homer/.m2/repository/org/forgerock/opendj/opendj-sdk-parent/3.0.0/opendj-sdk-parent-3.0.0.pom, line 112, column 21

Opendj-sdk-parent is taken from https://ox.gluu.org/maven/org/forgerock/opendj/opendj-sdk-parent/3.0.0/. I have another version of this artifact, but there's no significant differences between them.
It is problem with opendj-sdk-parent or I've missed something?

**Comment by maximthomas** [comment]
@13Homer you can build OpenDJ completely from sources as stated in README.md
```git clone --recursive  https://github.com/OpenIdentityPlatform/OpenDJ.git
mvn clean install -f OpenDJ/forgerock-parent
mvn clean install -f OpenDJ```

**Comment by 13Homer** [comment]
I did this exactly that way. Forgerock-parent built successfully, but main build has failed.

**Comment by maximthomas** [comment]
Could you attach maven full output to the issue?

**Comment by 13Homer** [comment]
I'll rebuid everything one again and attach build results only for OpenDJ.

**Comment by 13Homer** [comment]
[build-X.txt](https://github.com/OpenIdentityPlatform/OpenDJ/files/3368818/build-X.txt)
[build.txt](https://github.com/OpenIdentityPlatform/OpenDJ/files/3368819/build.txt)
Please find attached two versions: normal (mvn clean install) and with "-X" switch.

**Comment by maximthomas** [comment]
I don't see opendj-sdk-parent dependency for opendj-core:
```
$ mvn dependency:tree -f opendj-core | grep opendj-sdk
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
$
```
Checkout OpenDJ repo and, without any changes, remove .m2 folder and repeat build, or try build on clean machine

**Comment by 13Homer** [comment]
I'll do. Thank you.

**Comment by 13Homer** [comment]
Everything has built properly, removing .m2 helped. I have no idea what was wrong with repo. Thank you.

**Comment by maximthomas** [comment]
You are welcome!
