### ISSUE TITLE
ERROR org.apache.fop.hyphenation.Hyphenator  - Couldn't find hyphenation pattern for lang="en".

### ISSUE THREAD

**Issue by vharseko** [OpenIdentityPlatform/OpenDJ#8]
First maven command runs just fine and then the second one fails.

mvn clean install -f OpenDJ

Things go along fine until this:

INFO: Writing xml font file /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/fonts/DejaVuSerif-metrics.xml...
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] Building zip: /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/epub/index.epub
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/epub/man-pages for generated file(s)
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] Building zip: /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/epub/index.epub
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/epub/man-pages for generated file(s)
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/html/man-pages for generated secondary file(s)
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
Recoverable error
Failure reading jar:file:/home/hixson/.m2/repository/net/sf/docbook/docbook-xsl/1.78.1/docbook-xsl-1.78.1-ns-resources.zip!/docbook/html/0: JAR entry docbook/html/0 not found in /home/hixson/.m2/repository/net/sf/docbook/docbook-xsl/1.78.1/docbook-xsl-1.78.1-ns-resources.zip
[INFO] /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/html/man-pages/index.html has been generated.
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] Chunking output.
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/html/man-pages for generated secondary file(s)
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] Chunking output.
Recoverable error
Failure reading jar:file:/home/hixson/.m2/repository/net/sf/docbook/docbook-xsl/1.78.1/docbook-xsl-1.78.1-ns-resources.zip!/docbook/html/0: JAR entry docbook/html/0 not found in /home/hixson/.m2/repository/net/sf/docbook/docbook-xsl/1.78.1/docbook-xsl-1.78.1-ns-resources.zip
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/html/man-pages for generated file(s)
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
Recoverable error
Failure reading file:/home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx-sources/man-pages/olinkdb.xml: /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx-sources/man-pages/olinkdb.xml (No such file or directory)
Recoverable error
Failure reading file:/home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx-sources/man-pages/olinkdb.xml: /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx-sources/man-pages/olinkdb.xml (No such file or directory)
[INFO] See /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/manpages/man-pages for generated file(s)
[INFO] Man page output directory: /home/hixson/src/OpenDJ/opendj-doc-generated-ref/target/docbkx/manpages
[INFO] Processing input file: man-pages/index.xml
[INFO] Applying customization parameters after docbkx parameters
[INFO] targetFileExtension pdf
[INFO] type fo
0 [main] ERROR org.apache.fop.hyphenation.Hyphenator  - Couldn't find hyphenation pattern for lang="en".
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenDJ BOM ......................................... SUCCESS [  1.115 s]
[INFO] OpenDJ Directory Services Project .................. SUCCESS [  0.661 s]
[INFO] OpenDJ Core APIs ................................... SUCCESS [ 43.173 s]
[INFO] OpenDJ Doc Helper Maven Plugin ..................... SUCCESS [  5.044 s]
[INFO] OpenDJ Grizzly Transport Provider .................. SUCCESS [  9.271 s]
[INFO] OpenDJ CLI API ..................................... SUCCESS [  2.377 s]
[INFO] OpenDJ SDK Toolkit ................................. SUCCESS [ 41.771 s]
[INFO] OpenDJ SDK Examples ................................ SUCCESS [  4.290 s]
[INFO] OpenDJ Commons REST Adapter ........................ SUCCESS [  8.921 s]
[INFO] OpenDJ Maven Plugin ................................ SUCCESS [  2.644 s]
[INFO] OpenDJ Configuration API ........................... SUCCESS [ 30.936 s]
[INFO] OpenDJ Commons REST LDAP Gateway ................... SUCCESS [  2.534 s]
[INFO] OpenDJ Server NG ................................... SUCCESS [  3.543 s]
[INFO] OpenDJ Server ...................................... SUCCESS [01:51 min]
[INFO] OpenDJ Server Example Plugin ....................... SUCCESS [  3.761 s]
[INFO] OpenDJ Legacy ...................................... SUCCESS [  2.754 s]
[INFO] OpenDJ DSML Gateway ................................ SUCCESS [  6.630 s]
[INFO] OpenDJ embedded server examples .................... SUCCESS [ 11.407 s]
[INFO] OpenDJ account change notification handler for OpenIDM SUCCESS [  6.307 s]
[INFO] OpenDJ Doc Generated References .................... FAILURE [13:19 min]
[INFO] OpenDJ Packages .................................... SKIPPED
[INFO] OpenDJ Debian Packages Parent ...................... SKIPPED
[INFO] OpenDJ Debian Standard Package ..................... SKIPPED
[INFO] OpenDJ RPM Packages Parent ......................... SKIPPED
[INFO] OpenDJ SVR4 Packages Parent ........................ SKIPPED
[INFO] OpenDJ MSI Packages Parent ......................... SKIPPED
[INFO] OpenDJ Docker Packages Parent ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18:19 min
[INFO] Finished at: 2018-05-16T14:50:58-07:00
[INFO] Final Memory: 379M/1839M

**Comment by mbt-bs** [comment]
There is a workaround.
I've tried to add -e option to maven install and get exception:

[ERROR] Failed to execute goal org.forgerock.commons:forgerock-doc-maven-plugin:21.0.0-SNAPSHOT:build (build-man-pages) on project opendj-doc-generated-ref: Unable to execute mojo: Failed to transform to fo: org.apache.fop.fo.ValidationException: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895): null:34747:895: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895) -> [Help 1]

Looks like some problem in pdf templates. If you don't need a pdf type documentation, you can just remove or comment 607 line in OpenDJ/opendj-doc-generated-ref/pom.xml like this:

<formats combine.self="override>
	<format>man</format>
	<format>epub</format>
	<format>html</format>
	
	<format>webhelp</format>
	<format>xhtml5</format>
</formats>

This is just temporary workaround until problem will be resolved.

**Comment by mbt-bs** [comment]
There is a workaround.
I've tried to add -e option to maven install and get exception:

[ERROR] Failed to execute goal org.forgerock.commons:forgerock-doc-maven-plugin:21.0.0-SNAPSHOT:build (build-man-pages) on project opendj-doc-generated-ref: Unable to execute mojo: Failed to transform to fo: org.apache.fop.fo.ValidationException: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895): null:34747:895: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895) -> [Help 1]

Looks like some problem in pdf templates. If you don't need a pdf type documentation, you can just remove or comment 607 line in OpenDJ/opendj-doc-generated-ref/pom.xml like this:

```<formats combine.self="override>
	<format>man</format>
	<format>epub</format>
	<format>html</format>
	<!--<format>pdf</format>-->
	<format>webhelp</format>
	<format>xhtml5</format>
</formats>```
This is just temporary workaround until problem will be resolved.

**Comment by mbt-bs** [comment]
There is a workaround.
I've tried to add -e option to maven install and get exception:

[ERROR] Failed to execute goal org.forgerock.commons:forgerock-doc-maven-plugin:21.0.0-SNAPSHOT:build (build-man-pages) on project opendj-doc-generated-ref: Unable to execute mojo: Failed to transform to fo: org.apache.fop.fo.ValidationException: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895): null:34747:895: "fo:table-header" is missing child elements. Required content model: marker* (table-row+|table-cell+) (See position 34747:895) -> [Help 1]

Looks like some problem in pdf templates. If you don't need a pdf type documentation, you can just remove or comment 607 line in OpenDJ/opendj-doc-generated-ref/pom.xml like this:
```
<formats combine.self="override>
	<format>man</format>
	<format>epub</format>
	<format>html</format>
	<!--<format>pdf</format>-->
	<format>webhelp</format>
	<format>xhtml5</format>
</formats>
```
This is just temporary workaround until problem will be resolved.

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenDJ/commit/62aa935418029caf16f1bd7729b27ff768c00a25
