### ISSUE TITLE
Build `deb` package with additional default-jre-headless dependency

### ISSUE THREAD

**Issue by tntclaus** [OpenIdentityPlatform/OpenDJ#88]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am forced to install full JRE for cli apps in Debian/Ubuntu Server environment. 

Right now after installing opendj with following commands:
```
apt-get install default-jre-headless -y
dpkg -i --ignore-depends=default-jre opendj_4.4.3-1_all.deb
```

everything works pretty fine except I'm getting annoying message every time I try to install additional package:

```
root@localhost:~# apt-get install some-other-package
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 opendj : Depends: default-jre but it is not going to be installed or
                   java6-runtime or
                   java7-runtime
```
 

**Describe the solution you'd like**
OpenDJ doesn't need Java GUI in some (most?) cases, full JRE dependency is overkill. Feel free to correct me if I'm wrong.

**Describe alternatives you've considered**
It is possible to alter dependency in `opendj_X.Y.Z_all.deb` from `default-jre` to `default-jre-headless | default-jre`. e.g.:
`Depends: default-jre-headless | default-jre`

**Comment by vharseko** [comment]
thanks @tntclaus
